### ISSUE TITLE
Rename "mgmtmain" to libmgmt or lib?

### ISSUE THREAD

**Issue by purpleidea** [purpleidea/mgmt#103]
I suck at naming, so I'd like your advice. I'm considering renaming "mgmtmain" (which I think is a bad name) to either "libmgmt", or most likely "lib".

https://github.com/purpleidea/mgmt/tree/master/mgmtmain

This is the package which gets imported and used by the main stub,

https://github.com/purpleidea/mgmt/blob/master/main.go#L24

and also is what is imported if we use mgmt as a library.

https://github.com/purpleidea/mgmt/tree/master/examples/lib

So I'd love to hear your comments, suggestions, etc... If you have any alternate ideas, please LMK ASAP!

/cc @ffrank @vinzenz @joejulian @jumanjiman @tuxmea @BinaryTiger 

Thanks!

**Comment by joejulian** [comment]
I like libmgmt.

**Comment by purpleidea** [comment]
@joejulian Even if the import is

`github.com/purpleidea/mgmt/libmgmt`

with the "mgmt" string named twice?

**Comment by purpleidea** [comment]
BTW: Some of the material I mentioned here is now available as a blog post:

**Comment by tuxmea** [comment]
lib sounds very generic, but it seems to fit. better than libmgmt when you have the name twice.
so this is the place where we now place further extensions to mgmt into?
only internal extensions? then lib is fine
also external stuff? then ext would be better.

**Comment by vinzenz** [comment]
Well an alternative could be API, no? 

github.com/purpleidea/mgmt/api since this is what it is, or do I miss anything?

Anyway just a thought.

**Comment by ffrank** [comment]
FWIW I have zero trouble with `purpleidea/mgmt/libmgmt`. Visual elegance is a secondary concern at best.

And OTOH, if you were to qualify things with `lib.Main{}`, that is just extremely misleading. So the actual import would be

```
mgmt purpleidea/mgmt/lib
```

anyway (to alias it to plain `mgmt`), so what gives.

**Comment by purpleidea** [comment]
@ffrank RE: `mgmt purpleidea/mgmt/lib` -- i like this...

**Comment by purpleidea** [comment]
Fixed in https://github.com/purpleidea/mgmt/commit/4803be1987d50da9d662e846e83db94dc0dac2b3

Thanks to everyone for their feedback.

**Comment by ffrank** [comment]
Note to self: Stop including things you do not want in your opinion posts. Especially when formatting makes them the most prominent part of said post.

\_(ツ)_/¯

**Comment by purpleidea** [comment]
@ffrank wait did I mis-read your comment? I thought it was a +1 to that idea :P

**Comment by ffrank** [comment]
Well I did make it super confusing, so mea culpa.
