### ISSUE TITLE
Make some resources optional

### ISSUE THREAD

**Issue by mildred** [purpleidea/mgmt#114]
Some systems do not have all the libraries required to run mgmt. For example, CoreOS doesn't have libvirt. Have the ability to build mgmt without the virt resource would allow mgmt to run on CoreOS.

**Comment by purpleidea** [comment]
On Tue, Feb 7, 2017 at 11:34 AM, mildred <notifications@github.com> wrote:
>
> Some systems do not have all the libraries required to run mgmt. For example, CoreOS doesn't have libvirt. Have the ability to build mgmt without the virt resource would allow mgmt to run on CoreOS.

This is a fair point. Any recommendations on how we should solve this?

**Comment by roidelapluie** [comment]
It makes sense from a security perspective.

**Comment by mildred** [comment]
I tried build tags `// +build !nolibvirt` for example, but I couldn't make it work for some reason. But I think this is the way to do it.

**Comment by daenney** [comment]
@mildred Did you leave a newline between the build tag and the package declaration? If you don't it'll get interpreted as part of the package documentation instead.

I would suggest a tag like:

```go
// +build resource_all resource_virt
```

The official binaries that we produce can then build with `go build -tags resource_all` to include everything or explicitly go `go build -tags resource_virt` if we don't want to build with all resource types but do want to build with libvirt support.

Unfortunately, when I implemented that I hit a different snag:
```go
[I] 12:06:55 ~/D/g/s/g/p/mgmt (master) $ cat resources/virt.go
// Mgmt
// Copyright (C) 2013-2016+ James Shubin and the project contributors
// Written by James Shubin <james@shubin.ca> and the project contributors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// +build resource_all resource_virt

package resources
```

Trying to build it now without including the `resource_virt` tag gets me:

```sh
[I] 12:08:21 ~/D/g/s/g/p/mgmt (master) $ go build
# github.com/purpleidea/mgmt/yamlgraph
yamlgraph/gconfig.go:69: undefined: resources.VirtRes
```

Since the `resources.VirtRes` now isn't "defined" anymore a different part of the code base explodes.

**Comment by mildred** [comment]
> @mildred Did you leave a newline between the build tag and the package declaration? If you don't it'll get interpreted as part of the package documentation instead.

It must be before the package instruction, not after. I found this in #110

**Comment by daenney** [comment]
Oh yeah, sorry. I meant a newline between the package documentation and the build tag.

**Comment by mildred** [comment]
> I never said it must come after the package instruction. I only said you need to leave a new line after it, i.e the build tag. See my example code, which works.

I had no problem with that thanks to the vim syntax highlighting (when it is not separated by a newline, coloration doesn't work)

**Comment by purpleidea** [comment]
This is merged now. Closing.
