### ISSUE TITLE
mgmt name

### ISSUE THREAD

**Issue by roidelapluie** [purpleidea/mgmt#129]
I think we should look for a better name -- and I have an idea.

I think that instead of focusing on one name, we should focus on multiple names -- flavors.

What I mean is that if we only ship one flavor, then everyone will need e.g libvirt installed. That is a huge requirement.

My proposal is to find a name that we can decline in multiple flavour, so we can ship multiple binaries with different names.

e.g.:

## MusicMgmt

Pick your flavour:

| Name | Package | File | Service | Livbvirt | Augeas |
| - | - | - | - | - | - |
| Bagpipe | X | X | X | | | |
| Paixiao | X | X | X | |  X |
| Bandura | X | X | | | | X |
| Kadlong | X | X | X | X | X | X |

ofc music is just an example.

**Comment by purpleidea** [comment]
@roidelapluie Your enthusiasm is encouraging, however until we get to be minimally viable, and without a specific concrete recommendation for a new name, I'm going to have to close this. Sorry! Variable naming is hard!

Eg: https://xkcd.com/910/

As an aside, someone with better knowledge of how compiling/linking in golang works should tell us if there's a way we can compile in the libvirt code, but still have the binary work on machines if that isn't present. I'm sure there is...
