### ISSUE TITLE
mgmt does not error when there is an unsupported resource it its yaml file

### ISSUE THREAD

**Issue by roidelapluie** [purpleidea/mgmt#130]

**Comment by purpleidea** [comment]
Should it?
YAML file is just a struct for developers, not the user interface. That will come with the language. I'm going to close this issue for now and limit issues to ones that are major, or that come with patches,

**Comment by purpleidea** [comment]
@roidelapluie Why is that?

**Comment by roidelapluie** [comment]
It is important because:

- it is a prerequisite to the development of a language. Without this, testing a language will be very hard.
- if we plan to make e.g. support for libvirt optional, it is important to not allow a catalog with virt resources
- this is also important to check that the compiler understands and respects the compiler input. E.g Felix' puppet compiler is independant from mgmt.

**Comment by purpleidea** [comment]
@roidelapluie I partly agree, and I am fine not blocking this patch. However, is it possible at the moment? The yaml parsing code is here: https://github.com/purpleidea/mgmt/blob/master/yamlgraph/gconfig.go#L73

Is there a way to do this?

**Comment by purpleidea** [comment]
(Basically the YAML module takes a struct in the right format and blasts anything that matches into it, while ignoring additional items...) If we could have it error if it had additional items not blasted in, that would be fine with me.

**Comment by roidelapluie** [comment]
I will have a look
