### ISSUE TITLE
create a timer resource

### ISSUE THREAD

**Issue by purpleidea** [purpleidea/mgmt#15]
We could have a timer resource in mgmt!

The idea would be to basically simulate some of the timer stuff I wrote in puppet, but more elegantly of course:
https://ttboj.wordpress.com/2012/11/14/setting-timed-events-in-puppet/

The timer resource could trigger after N seconds, and in addition could support different algorithms for incrementing, eg: linear, exponential, etc... so that you can trigger timers in different ways.

You might want to have different options about when to reset the timer, eg: on recompile, or not, and so on...

Experiment, and have a little fun! I hope someone gets to this before I do, because it should be a pleasure to write!

**Comment by sharadgana** [comment]
I would like to take a shot at this . Is this a good issue to start working on without knowing all of the mgmt internals ?

**Comment by purpleidea** [comment]
Hi @sharadgana please do! You only need to learn how to implement the basic resource API, which is quite straight forward. Have a look at pkg.go for the basic layout of a more complex resource, or noop.go for the most basic one. Please ping me if you have any questions, and feel free to join us in #mgmtconfig on Freenode IRC too.

**Comment by purpleidea** [comment]
If someone wants to add additional algorithms to this resource, or implement automatic grouping, please do! I'm not sure the later is really necessary, but I'm happy to merge it if it would be good practice for someone or if someone thinks of a good use case.
