### ISSUE TITLE
Automatic propagation of resource graph through etcd

### ISSUE THREAD

**Issue by mildred** [purpleidea/mgmt#162]
I work for a product, [squarescale](http://github.com/squarescale/) and we are going to use mgmt to provision the nodes we maintain. There is a feature that we'd have expected from mgmt, and I thought we could discuss of it here.

We already have clusters of nodes maintained though etcd. All those nodes share the same configuration, and instead of pushing the YAML resource graph to all the nodes, it would have been nice if we could push the resource graph to the etcd cluster.

This could work well with a custom DSL. Say for instance you run on your laptop the DSL compiler, it compiles it to a resource graph that it pushed it directly to etcd. Then all nodes are configured to pull resources from etcd.

Do you think this is something that is desirable for mgmt? Would that be how it works? How did you imagine it?

**Comment by purpleidea** [comment]
@mildred Would it be helpful if we setup a ghangout and had a discussion about it so that I could understand better, and tell you a bit about what we're planning to see if this fits your needs? LMK, feel free to PM me on IRC or email me.

**Comment by purpleidea** [comment]
@mildred Ping-- Should I keep this open, did you want to chat more about this? LMK.

**Comment by mildred** [comment]
I didn't see my notifications during that time. I'm on european timezone, and I should be available for a chat to talk about this if you want.

**Comment by purpleidea** [comment]
@mildred Sure, LMK when. How about in a week on Tuesday? Should give you time to see the notifications. Maybe send me an email and I can send you meeting details. My GH id at gmail or PM on IRC.

**Comment by purpleidea** [comment]
Looking through old issues and I'm happy to report this has been implemented a while back. It's called "deploys" and it works with either the DSL code, or yaml, etc...

There's no blog post about it yet, but happy to explain/demo it if anyone is blocked by not having this yet.
