### ISSUE TITLE
[LOVE] Our GAPI needs a tweak

### ISSUE THREAD

**Issue by purpleidea** [purpleidea/mgmt#174]
This is intended for a new mgmt contributor or for someone with very few patches. If nobody claims this, but you are *really* itching to write this, that's okay too!

In mgmt we have a GAPI (graph API) which any frontend can implement to generate graphs that the mgmt engine will run. Currently we have a raw yaml graph input, and a puppet code input. When the mgmt language is built, it will use this API as well.

(Links to code are at an arbitrary git commit so that they don't break, but obviously you'll want to do this on git master and some things might have moved slightly if we've patches those files. Ping me if you can't find something.)

Here is the interface:
https://github.com/purpleidea/mgmt/blob/73ccbb69ea1d74ab5fd96b2096d5902313588a59/gapi/gapi.go#L44

The `Next()` function spits out events when there are new graphs available. In particular, when new "exported resources" are available (from other machines) we refresh our local graphs.

That stream of events is currently located here:
https://github.com/purpleidea/mgmt/blob/73ccbb69ea1d74ab5fd96b2096d5902313588a59/lib/main.go#L377

But it should actually be hidden inside the GAPI itself, since not every GAPI might necessarily want to Watch for exported resources.

So, that function should be moved out of there, and into the GAPI, eg here:
https://github.com/purpleidea/mgmt/blob/73ccbb69ea1d74ab5fd96b2096d5902313588a59/yamlgraph/gapi.go#L79

but to wrap it nicely, we'd like to actual have a generic interface for that watch called `ResWatch` which should go here:

https://github.com/purpleidea/mgmt/blob/73ccbb69ea1d74ab5fd96b2096d5902313588a59/gapi/gapi.go#L29

The implementation of that function will probably USE the WatchAll method, and go in here:

https://github.com/purpleidea/mgmt/blob/73ccbb69ea1d74ab5fd96b2096d5902313588a59/etcd/world.go#L30

Hopefully this is clear enough, if you have questions please let me know!

Happy hacking!

**Comment by snowsky** [comment]
I just got started on mgmt and found it helpful for the daily work. I will give it a shot to see if I can work it out.

**Comment by purpleidea** [comment]
@snowsky Awesome... Are you claiming this issue?

**Comment by snowsky** [comment]
@purpleidea Yes, I am.

**Comment by purpleidea** [comment]
@snowsky Awesome! If you have any questions please lmk.

**Comment by snowsky** [comment]
@purpleidea how do I generate and view the graph?

**Comment by snowsky** [comment]
@purpleidea so I will add the other function named ResWatch for GAPI. I don't know why "etcd.WatchAll(EmbdEtcd)" was mentioned. Is etcd struct related to GAPI?

**Comment by purpleidea** [comment]
@snowsky You can generate the graph by running mgmt like: `mgmt run --yaml examples/whatever.yaml` If you want to visualize try the `--graphviz` option.

The `etcd.WatchAll` is the implementation of the interface we'll add to the GAPI.

**Comment by purpleidea** [comment]
@snowsky Any progress on this? Thanks

**Comment by snowsky** [comment]
@purpleidea run into some issue of etcd:
```
22:15:39 etcd.go:312: Etcd: Connect: Endpoints: []
22:15:39 etcd.go:326: Etcd: Connect: CtxError...
22:15:39 etcd.go:595: Etcd: CtxError: Reason: CtxDelayErr(2s): No endpoints available yet!
```
I have removed /var/lib/mgmt after googling, but it still shows the error message.

**Comment by purpleidea** [comment]
@snowsky try running mgmt with `--tmp-prefix`.
If you still see the issue, please paste the full command you're running.

**Comment by snowsky** [comment]
```
root@ubuntu-xenial:~/go/src/github.com/purpleidea/mgmt# time ./mgmt run --yaml examples/graph0.yaml --converged-timeout=5 --tmp-prefix --graphviz graph
22:17:59 main.go:194: This is: mgmt, version: 0.0.10-15-g660554c
22:17:59 main.go:195: Main: Start: 1489616279939605810
22:17:59 main.go:219: Main: Warning: Working prefix directory is temporary!
22:17:59 main.go:225: Main: Working prefix is: /tmp/mgmt-ubuntu-xenial-266501871
22:18:00 pgp.go:88: PGP: Created key: 381AFE25
22:18:00 main.go:308: Main: Seeds: No seeds specified!
22:18:00 etcd.go:397: Etcd: Bootstrapping...
22:18:00 etcd.go:1397: Etcd: Nominated: ubuntu-xenial=http://127.0.0.1:2380
22:18:00 etcd.go:1412: Etcd: StartServer(newCluster: true): ubuntu-xenial=http://127.0.0.1:2380
22:18:00 etcd.go:1666: Etcd: StartServer: Starting server...
22:18:00 etcd.go:312: Etcd: Connect: Endpoints: []
22:18:00 etcd.go:326: Etcd: Connect: CtxError...
22:18:00 etcd.go:595: Etcd: CtxError: Reason: CtxDelayErr(1s): No endpoints available yet!
22:18:00 etcd.go:409: Etcd: Startup: Volunteering...
22:18:01 etcd.go:312: Etcd: Connect: Endpoints: []
22:18:01 etcd.go:326: Etcd: Connect: CtxError...
22:18:01 etcd.go:595: Etcd: CtxError: Reason: CtxDelayErr(2s): No endpoints available yet!
^C22:18:02 cli.go:134: Interrupted by ^C
^C22:18:03 etcd.go:312: Etcd: Connect: Endpoints: []
22:18:03 etcd.go:326: Etcd: Connect: CtxError...
22:18:03 etcd.go:595: Etcd: CtxError: Reason: CtxDelayErr(3s): No endpoints available yet!
^C22:18:06 etcd.go:312: Etcd: Connect: Endpoints: []
22:18:06 etcd.go:326: Etcd: Connect: CtxError...
22:18:06 etcd.go:595: Etcd: CtxError: Reason: CtxDelayErr(4s): No endpoints available yet!
22:18:10 etcd.go:312: Etcd: Connect: Endpoints: []
22:18:10 etcd.go:326: Etcd: Connect: CtxError...
22:18:10 etcd.go:595: Etcd: CtxError: Reason: CtxDelayErr(5s): No endpoints available yet!
22:18:15 etcd.go:312: Etcd: Connect: Endpoints: []
22:18:15 etcd.go:318: Etcd: The dataDir (/tmp/mgmt-ubuntu-xenial-266501871/etcd) might be inconsistent or corrupt.
22:18:15 etcd.go:319: Etcd: Please see: https://github.com/purpleidea/mgmt/blob/master/DOCUMENTATION.md#what-does-the-error-message-about-an-inconsistent-datadir-mean
22:18:15 etcd.go:352: Etcd: Startup: Error: can't find an available endpoint
```

**Comment by purpleidea** [comment]
@snowsky Can you:

```
ps auxww | grep mgmt
```

and see if you have an existing mgmt running?

**Comment by purpleidea** [comment]
(like some old one running that hung or that you have in a terminal...)

**Comment by snowsky** [comment]
Didn't see any:
```
root@ubuntu-xenial:~/go/src/github.com/purpleidea/mgmt# ps auxww | grep mgmt
root      7832  0.0  0.0  14224  1012 pts/0    S+   22:28   0:00 grep --color=auto mgmt
```

**Comment by purpleidea** [comment]
(It would be easier and faster to debug this on IRC btw, ping me in #mgmtconfig on Freenode)

Can you check your deps, eg: `git submodule init && git submodule update` in the mgmt dir?

**Comment by purpleidea** [comment]
@snowsky Also you might want to check:

```ps auxww | grep go```

and

```ps auxww | grep run```

and

```ps auxww | grep etcd```

I was fairly certain it was due to an existing artifact... Maybe not though.

**Comment by purpleidea** [comment]
(in case it was running as a different name in case you used `go run` or something.

**Comment by snowsky** [comment]
```
root@ubuntu-xenial:~/go/src/github.com/purpleidea/mgmt# git submodule
 e2d51961dd4abe6540c7d8e4aac0da7addf2e16e vendor/github.com/coreos/etcd (v3.1.0-alpha.1-13-ge2d5196)
 acebe0f9ff5993e130b141ee60e83e592839ca22 vendor/github.com/grpc-ecosystem/grpc-gateway (v1.1.0-13-gacebe0f)
 6192533ebb4662c3bc0ce60c1d33dfc6702a1eac vendor/github.com/purpleidea/go-systemd (v13-13-g6192533)
 231b4cfea0e79843053a33f5fe90bd4d84b23cd3 vendor/google.golang.org/grpc (v1.0.0-183-g231b4cf)
 7be54206639f256967dd82fa767397ba5f8f48f5 vendor/gopkg.in/fsnotify.v1 (v1.2.1)
 1e2ddf1bad06f9e1cfdd62dd909c4fcb7f82e114 vendor/honnef.co/go/augeas (1e2ddf1)
root@ubuntu-xenial:~/go/src/github.com/purpleidea/mgmt# git submodule init && git submodule update
root@ubuntu-xenial:~/go/src/github.com/purpleidea/mgmt# echo $?
0
```

I just joined IRC with the same name as @snowsky

**Comment by purpleidea** [comment]
@snowsky Thanks again for your work so far... Due to some patches I am working on (not yet posted) it looks like this issue will block some of that work and testing that I am doing. As a result if you're not able to finish this shortly, I might have to take over and patch it myself. :(

I do apologize, because I have no desire to rush anyone on a patch, rather I didn't realize it was an issue which would have blocked any other work.

So please let me know either way if you'll be finishing soon or if it will take a while. If it's the latter, then there are other LOVE issues if you're not able to merge this soon.

Thanks for your understanding.

**Comment by snowsky** [comment]
@purpleidea no worries, something came up recently, please take it and I will follow up later. Sorry for not fixing it soon.

**Comment by purpleidea** [comment]
This is fixed in https://github.com/purpleidea/mgmt/commit/6fd5623b1f97cbfd77399a78d2aec14ae986ff2e

Have a look at the commit if you're curious. Cheers!
