### ISSUE TITLE
[LOVE] pgraph->DeleteEdge needs test cases

### ISSUE THREAD

**Issue by purpleidea** [purpleidea/mgmt#175]
This is a beginner patch for a new golang/mgmt contributor!

The DeleteEdge methood in pgraph (currently at: https://github.com/purpleidea/mgmt/blob/master/pgraph/pgraph.go#L192 ) needs some tests!

Please write some! Tests should go in pgraph_test.go

Happy hacking!

**Comment by taksuyu** [comment]
Seems doable. I'll give it a shot.

**Comment by purpleidea** [comment]
@taksuyu Any progress on this? Thanks

**Comment by taksuyu** [comment]
I may have to just push out something simple. Been a bit busy with stuff. Sorry about that.

**Comment by taksuyu** [comment]
https://github.com/purpleidea/mgmt/pull/181

**Comment by dreamer-nitj** [comment]
I will take it up

**Comment by dreamer-nitj** [comment]
How do i run the test case.. i get this error:

`go run ./pgraph/pgraph_test.go 
go run: cannot run *_test.go files (./pgraph/pgraph_test.go)`

**Comment by purpleidea** [comment]
`go test github.com/purpleidea/mgmt/pgraph`

OR

`go test github.com/purpleidea/mgmt/pgraph -v`

OR

`go test github.com/purpleidea/mgmt/pgraph -run TestCaseName`

**Comment by purpleidea** [comment]
Closed in https://github.com/purpleidea/mgmt/commit/db6972638d6663d6bca02595776f092a9a6ce430
