### ISSUE TITLE
golint has to be installed before running test.sh

### ISSUE THREAD

**Issue by snowsky** [purpleidea/mgmt#178]

**Comment by purpleidea** [comment]
If you run make-deps: https://github.com/purpleidea/mgmt/blob/master/misc/make-deps.sh#L82 then it is installed.

AFAIK there isn't a bug here, unless there's something you think we should patch?

**Comment by snowsky** [comment]
Yes, that will work. I may miss --recursive parameter and then when make build failed on the other VM.

**Comment by purpleidea** [comment]
Cool! Closing issue then, LMK if you have more questions.
