### ISSUE TITLE
[LOVE] set the etcd max transaction limit

### ISSUE THREAD

**Issue by purpleidea** [purpleidea/mgmt#196]
This should be a beginner level patch for someone who is either new-ish to golang, or new to mgmt. It is meant to encourage new programmers to get involved with mgmt.

In etcd there are transactions which are composed of a number of operations. There was previously a constant limit to the number of ops per transaction to avoid blocking other clients. The default limit was too small for most users, so it's now a configurable setting.

For this patch, we should set this to a reasonable default. The upstream change is here: https://github.com/coreos/etcd/pull/7976

The patch would likely need to add our own constant, and this would be in etcd/etcd.go where we have the embed code.

Happy hacking, and ping me for questions!

**Comment by nitinprakash96** [comment]
Hi, I'd like to work on this.!

**Comment by purpleidea** [comment]
@nitinprakash96 Great... Need any pointers to get started or have any questions? If so, please ping purpleidea in #mgmtconfig on Freenode.

**Comment by purpleidea** [comment]
This is where the embed server code is, which is where this would need to be hooked in:

https://github.com/purpleidea/mgmt/blob/master/etcd/etcd.go#L1650

**Comment by purpleidea** [comment]
NOTE: this has been fixed in https://github.com/purpleidea/mgmt/pull/200 and is waiting on merge.

**Comment by purpleidea** [comment]
merged in https://github.com/purpleidea/mgmt/commit/24cb2e6450bae2cfecfa7322695d6b6eeec14c19

Thanks again, and sorry for our misfire in thinking the patch would have worked earlier. Please let us know if we can help you get involved with any other issues.
