### ISSUE TITLE
[LOVE] Validate the msg resource properly

### ISSUE THREAD

**Issue by purpleidea** [purpleidea/mgmt#203]
This should be a beginner level patch for someone who is either new-ish to golang, or new to mgmt. It is meant to encourage new programmers to get involved with mgmt.

We have a `msg` resource in mgmt, As you can see here: https://github.com/purpleidea/mgmt/blob/master/resources/msg.go#L97 someone didn't Validate the obj.Priority string in the Validate method.

Validate is part of the resource API: https://github.com/purpleidea/mgmt/blob/master/docs/resource-guide.md#validate

Add the necessary patch to check these! If this takes you more than one hour after you've got the hello world example building, or if you have any questions, please ping us in #mgmtconfig on Freenode IRC.

Thanks and happy hacking!

**Comment by dkliban** [comment]
I am working on this.

**Comment by purpleidea** [comment]
This patch should also include a test case. It should be similar in approach to https://github.com/purpleidea/mgmt/blob/master/resources/exec_test.go#L24

In particular it should test the Validate method.

You can run the tests locally like this:

go test github.com/purpleidea/mgmt/resources

OR

go test github.com/purpleidea/mgmt/resources -v

OR

go test github.com/purpleidea/mgmt/resources -run TestCaseName

**Comment by dkliban** [comment]
https://github.com/purpleidea/mgmt/pull/206

**Comment by purpleidea** [comment]
@dkliban killed this in https://github.com/purpleidea/mgmt/commit/1003b49dd95456172e2527b1f2f408fa7f748ee0 w00t!
