### ISSUE TITLE
[LOVE] implement a user resource

### ISSUE THREAD

**Issue by purpleidea** [purpleidea/mgmt#215]
#### Intro:

This is a medium level patch for someone who is past being a golang beginner, but is new to mgmt. It is meant to encourage new programmers to get involved with mgmt. It will probably take you at *least two days* of coding and testing.

In traditional config management systems there is a "user" resource. We'd like to add one in mgmt as well. You'll want to be at least casually familiar with the https://github.com/purpleidea/mgmt/blob/master/docs/resource-guide.md first.

To implement this, you'll need to either recommend an alternate design, or use the one provided below. This hasn't been exhaustively investigated, so comments are welcome!

#### Design:

We need to add/modify/remove users as well as watch for changes. Adding, modifying, and removing users should be done with the `useradd`, `usermod` and `userdel` commands. Watching for changes should be done with an inotify handle on `/etc/passwd`. To actually "read the file" you can use the golang https://golang.org/pkg/os/user/ package.

Instead of using the os/exec and inotify functions directly, this should be a composite resource which uses the mgmt exec and mgmt file resources and builds on top of them. There are some partial (and hopefully correct) examples of this in https://github.com/purpleidea/mgmt/blob/master/resources/nspawn.go and https://github.com/purpleidea/mgmt/blob/0df4824a56678a8f2173838ff58817b22feefee9/resources/graph.go -- I believe some of the Init code in graph.go is incorrect. 

I recommend starting with the basic `CheckApply` part of the resource, and once that is solid, then writing the `Watch` method. You can use the `Poll` metaparameter ( https://ttboj.wordpress.com/2017/03/01/metaparameters-in-mgmt/ ) for testing purposes before you've implemented `Watch`.

Think about which properties the `UserRes` struct that your implementing should have. Start with the *minimum*. Don't even consider the `password` aspect (at least for now).

This should be challenging, but rewarding.

Read the contributions tips:
https://github.com/purpleidea/mgmt/blob/master/.github/PULL_REQUEST_TEMPLATE.md

Happy hacking, and ping me for questions!

#### Bonus/Future work:

* Add automatic edges ( https://ttboj.wordpress.com/2016/03/14/automatic-edges-in-mgmt/ ) between this resource and any other resource that might be appropriate. Eg: `file` for user fields there, path for home dir path, and so on... Leave any ideas for other automatic edges in the comments.

* Add a group resource. The same rough design applies, and it could have automatic edges to this one.

* Implement send/recv ( https://ttboj.wordpress.com/2016/12/07/sendrecv-in-mgmt/ ) for some of the properties. Uid comes to mind as a value to send once a user is created by name. Password is probably a value to consider receiving.

**Comment by purpleidea** [comment]
Prior art: As a bit of corroboration for our design, it seems that the cockpit project takes this approach as well as found in: https://github.com/cockpit-project/cockpit/blob/master/pkg/users/local.js

I think the systemd project should wrap /etc/passwd and provide a nice API :)

**Comment by jonathangold** [comment]
I'd like to work on this.

**Comment by purpleidea** [comment]
Here are my initial thoughts on what the "primary key" should be and username vs. uid. I think the username (our key) should be the main reference to the user. The uid should be a *uid which if set will ask our resource to set this particular uid. If not it will be automatically assigned. It can become a sent value if unspecified.

The easiest way to implement is to ignore uid initially and add it in a later patch. HTH

**Comment by roidelapluie** [comment]
UID can not be the primary key as the same UID can be assigned to 2 users

**Comment by purpleidea** [comment]
@roidelapluie I thought it was that the same username could exist as two different UID's? (Which we wouldn't support anyways) -- got a reference?

**Comment by roidelapluie** [comment]
man useradd

```

       -o, --non-unique
           Allow the creation of a user account with a duplicate (non-unique)
           UID.

           This option is only valid in combination with the -u option.

```

**Comment by purpleidea** [comment]
That settles it!

**Comment by purpleidea** [comment]
PS: I'm having second thoughts about a "core" resource like user needing to be composite. While there might be some benefits, I think there will also be some memory overhead and possibly unneeded complexity.

While I still think it's important to "DRY", here's an example for Watch:

https://github.com/purpleidea/mgmt/blob/master/resources/augeas.go#L101

We probably need the same code (modulo the file path) for user watching /etc/passwd so perhaps it's worth it to port this Watch to a Util function in resources, and just use that in both places?

Thoughts?

**Comment by jonathangold** [comment]
Do we want to allow for non-unique UIDs? if not, the field won't be applied if there is already a user with the desired UID.

**Comment by purpleidea** [comment]
@jonathangold We should probably not allow this by default, but include an option (A bool in the Struct) like AllowDuplicateUid which if true, sets the `--non-unique` option.

**Comment by purpleidea** [comment]
This is now closed in https://github.com/purpleidea/mgmt/commit/831c7e2c326e4fcbdec33f41cf7e0b2be433cdc5 :)

For future discussions (longer term) see: https://github.com/purpleidea/mgmt/issues/219
