### ISSUE TITLE
Tests (can) fail with Ruby 2.1.5

### ISSUE THREAD

**Issue by ffrank** [purpleidea/mgmt#23]
The YAML format test works by making Ruby parse the YAML, then re-serialize the result. However, on my machine (Debian 8) the output of the YAML module is a little arbitrary. Observe:

```
 irb(main):009:0> puts YAML.dump( { :all => { :content => "This\nis\nstupid.\n", :path => "/this/is/not" } } )

---
:all:
  :content: |
    This
    is
    stupid.
  :path: "/this/is/not"
=> nil
irb(main):010:0> puts YAML.dump( { :all => { :content => "This\n", :path => "/this/is/not" } } )

---
:all:
  :content: 'This

'
  :path: "/this/is/not"
=> nil
irb(main):011:0> puts YAML.dump( { :all => { :content => "This is demo\n", :path => "/this/is/not" } } )

---
:all:
  :content: 'This is demo

'
  :path: "/this/is/not"
=> nil
irb(main):012:0> puts YAML.dump( { :all => { :content => "This is demo\n\n", :path => "/this/is/not" } } )

---
:all:
  :content: "This is demo\n\n"
  :path: "/this/is/not"
=> nil
irb(main):013:0> puts YAML.dump( { :all => { :content => "This is demo\nWhat\n", :path => "/this/is/not" } } )

---
:all:
  :content: |
    This is demo
    What
  :path: "/this/is/not"
=> nil
irb(main):014:0> RUBY_VERSION
=> "2.1.5"
```

Specifically, the strings in the example graphs are almost always represented in quoted form:

```
$ ruby -e "require 'yaml'; puts YAML.load_file('$i').to_yaml.each_line.map(&:rstrip).join(10.chr)+10.chr" 2>/dev/null

---
graph: mygraph
resources:
  file:
  - name: file1
    meta:
      autoedge: true
    path: "/tmp/foo/bar/f1"
    content: 'i am f1

'
    state: exists
  - name: file2
    meta:
      autoedge: true
    path: "/tmp/foo/"
    content: 'i am f2

'
    state: exists
edges: []
```

Seems to me that Ruby is not a safe way to run this test in this particular form. But then, I'm not even sure this is a very useful test to have, honestly. I'd rather see unit or integration tests that make sure that `mgmt` behaves correctly given the respective graph.

**Comment by purpleidea** [comment]
I have indeed noticed some non-determinism based on what version of ruby people are running. I also agree that there are more important kinds of tests to write. If your patches fail because of the ruby fmt test, comment it out, and if it fails on ci, then i'll comment it out in git master. Does that work?

**Comment by purpleidea** [comment]
For some background, when I learned about gofmt I was on a bit of a kick and trying to add formatting tests for everything :P

**Comment by purpleidea** [comment]
I'm going to close this due to inactivity, and because it seems most people (including all of travis) are on newer versions now.
