### ISSUE TITLE
[LOVE] docs: add mgmt to software directory

### ISSUE THREAD

**Issue by purpleidea** [purpleidea/mgmt#233]
This is a beginner issue for someone who'd rather do a small amount of text writing instead of code.

Please add mgmt to the directory: https://directory.fsf.org/wiki/Main_Page

I've never done this before, so please feel free to ask any questions you have here or in the IRC channel #mgmtconfig on Freenode.

Thanks!

**Comment by ikrauchanka** [comment]
the form has been submitted, waiting for review, I'm not sure how fast it will go.
Mgmt is listed under Category/System-administration/configuration/.

**Comment by purpleidea** [comment]
This seems to now be listed here: https://directory.fsf.org/wiki/Mgmt
So I guess we can close this :)

Thanks!
