### ISSUE TITLE
implement a libvirt resource

### ISSUE THREAD

**Issue by purpleidea** [purpleidea/mgmt#25]
Here is some background: https://www.redhat.com/archives/libvir-list/2016-April/msg00169.html

This looks like one of the most promising libraries to use, but alternative suggestions are encouraged: https://github.com/rgbkrk/libvirt-go ("encouraged", because the amount of analysis I've done is minimal).

Let me know if you're interested. This is most definitely an intermediate level project, but suitable for someone not very familiar with mgmt internals.

**Comment by nseps** [comment]
I'm working on this.

**Comment by purpleidea** [comment]
@nseps Great! Let me know if you have any questions about the Res interface.

**Comment by purpleidea** [comment]
@nseps told me to do an initial review of: https://github.com/nseps/mgmt/blob/virt_resource/ and I didn't know where to put it, so I'm doing it here...

1) https://github.com/nseps/mgmt/blob/virt_resource/virt.go#L67
Good question, do something like:
>	# FIXME: error...
>	log.Fatalf("error...", err)
>	return

for now, and once our interface supports errors properly, we'll update this! This is my bad :) Also s/faild/failed/

2) You should format your code with `gofmt`, you can do this with: `gofmt -w filename.go`, or run `make format` which will do it to all files.

3) https://github.com/nseps/mgmt/blob/virt_resource/virt.go#L101 You can do obj.Name instead of obj.BaseRes.Name

4) https://github.com/nseps/mgmt/blob/virt_resource/virt.go#L96 Unless there is the *need* to buffer your channels, don't do this. If this is required because libvirt won't keep the events pending when they're not read immediately (like DBus) then this is okay. If you want to avoid bursts and you want to group events together, the only way I know is to use a channel of size one, and when you receive a new event, only add it if len(mychan) == 0. I'm happy to discuss/debate these points if anyone knows better or differently. There might be a better way that I don't know.

5) Use log.Print... instead of fmt.Print...

6) Here's something more of substance: https://github.com/nseps/mgmt/blob/virt_resource/virt.go#L122 you do all of this checking in Watch() instead of in CheckApply() ... My first impression is that you should move it into CheckApply... If there's a good reason it should stay there instead, let me know. It's always good to get a different perspective and to either correct or reinforce the assumptions that I've made.

7) https://github.com/nseps/mgmt/blob/virt_resource/virt.go#L216 You have lots of these !apply blocks interspersed everywhere... I didn't try, but my guess is you can probably refactor this to make it a bit less redundant. I'm happy to be wrong if there's a good reason.
```
	if !apply {
		return false, nil
	}
```

I did this review fairly quickly, and I didn't run or test the code, since I got the idea you wanted some quick initial feedback before continuing deeper. Overall it looks very promising, and I'm looking forward to seeing more. In particular, I'm excited about the prospect of being about to pass in a kickstart file and having a machine get installed from scratch, for example.

Lastly, next time feel free to open a pull request, and I can comment there. Doesn't mean we have to merge it if it's still a WIP. Thanks again!

**Comment by mohae** [comment]
1) The example should include a format string since it is log.Fatalf().  I'd hope that, in the near future, there is some way to properly handle the error and/or propogate it back instead of just doing a log.Fatal.  IMO, that should only be done from `main()`

2) If you're a vim user vim-go, https://github.com/fatih/vim-go, plugin is the easiest way to ensure that your code is properly formatted.  For atom there's https://github.com/joefitzgerald/go-plus which includes other plugins.  For emacs there's https://github.com/dominikh/go-mode.el.  

I think most IDEs that support Go, along with LiteIDE, automatically format on save (though don't quote me on that as I don't use ide's outside of the occasional use of LiteIDE.)

4) The suggested method is racy.  If there is a need to group events together, maybe a struct should be defined/passed that includes a field that supports event information to allow the receiver to group them.  Another option would be to pass an int that signals the delimiting of event groups.  

I agree with don't buffer channels.  It's generally better to create backpressure than to buffer as one is just delaying the back-pressure point.  There are situations for which buffers are fine but they tend to be more limited than most assume.  If a channel is buffered there should be a good reason for it and a good reason for the buffer size other than some arbitrary value.  https://blog.golang.org/pipelines has an example of such a situation where the error channel has a buffer of 1, while doing parallel digestion, so that a deadlock doesn't occur.

**Comment by purpleidea** [comment]
@mohae 

> 1) The example should include a format string since it is log.Fatalf(). I'd hope that, in the near future, there is some way to properly handle the error and/or propogate it back instead of just doing a log.Fatal. IMO, that should only be done from main()

Completely agreed. As I mentioned this is just because I haven't worked out the error interface yet. It will depend on one more mechanic which I'm working on now.


> I'm not sure what @purpleidea meant by grouping events together

Sorry, what I meant was that suppose two events from libvirt happen very quickly before we're able to process them by running CheckApply(). The Watch() method could skip sending sending the second, third, etc, event if it knows the first one hasn't been used up or acted upon yet. We know this is the case if we use a buffered channel of 1, and we still see that message in the channel `len(channel) == 1`. In this case, we can discard the current event.

**Comment by nseps** [comment]
@purpleidea 

1,2,3,5) Got it!

4) 10 was just an arbitrary number. Thanks for the explanation. I have nearly zero experience with channels. I think size 1 channel will work. My question is do we discard subsequent events and only send the first or do we discard everything and send the last? For example, if the domain is stopped and we start(create) it, libvirt will send resumed_event and then started_event nearly at the same time in that order. In this case we care about started, even though resumed tell us what we need to know.

6) This must be my lack of understanding of what Watch() should do. If we get an event from libvirt, should we propagate it without checking the state? How do we decide what events are being sent or dropped? My understanding was if the event makes state dirty, send it. Please advise.

7) Ah, this is a tricky one. CheckApply() should check if the state is valid and if apply == true && state != valid proceed with some actions. At first i coded everything with if invalid -> action = do_this to avoid checking if apply is true. After all checks, if apply == true then -> another block of conditionals to determine what the actions are and apply them. But with this implementation i got rid of a bunch of vars, if and case statements with redundant if !apply blocks. Imagine if we start having disks, networks, etc. for the VMs. Each will have it's own state and stuff that will need checking. At some point i think CheckApply (for Virt res at least) will need to break to smaller functions that will behave the same way. Check state -> if apply == true && state != valid -> fix it else -> return false, nil. Maybe there is an obvious way to solve this that i am missing.

Thanks for reviewing and the feedback! Next time i'll PR. Just to give you a new prospective, imagine this in combination with cloud-init :)

**Comment by mohae** [comment]
Checking the len of a channel is still racy and should not be relied upon as things operating where race conditions may occur cannot be deemed either reliable or safe.  Either the consumer of the channel should be handling this, assuming a single consumer, or a mechanism other than channels should be used, especially when there are multiple consumers.

**Comment by purpleidea** [comment]
@nseps ping... Any chance you've made some progress on this, or would at least like to get what parts you do have merged so others can continue?

**Comment by mikefaille** [comment]
Just in case, it exist one popular libs to manage libvirt in go. This libs is used by docker-machine-driver-kvm : https://github.com/rgbkrk/libvirt-go.
@mohae If you have time to check, it could help your work to integrate libvirt to mgmt.

**Comment by purpleidea** [comment]
@mikefaille The original version of this patch is already using this lib. It's not @mohae who did this work but @nseps.

@mikefaille If you'd like to work on this patch, let us know.

**Comment by kshred** [comment]
I'm interested in having a look at this.

**Comment by purpleidea** [comment]
Fixed in https://github.com/purpleidea/mgmt/commit/8381d8246a522b46bf297aa915dfe3889870a9e6 and the subsequent patches that are now in git master. There is still a lot to add, but I'm going to close this ticket for now. Additional patches welcome! Ping me if you're looking for something to do on this.
