### ISSUE TITLE
[LOVE] Change Res API from Compare to Cmp

### ISSUE THREAD

**Issue by purpleidea** [purpleidea/mgmt#308]
#### EDIT:

This is 90% done, what remains is listed here: https://github.com/purpleidea/mgmt/issues/308#issuecomment-443588101

#### Welcome:

This is a beginner to intermediate level patch for someone who is new to golang, and is new to mgmt. It is meant to encourage new programmers to get involved with mgmt. It will probably take you a few hours to a day or so to complete.

#### Intro:

Mgmt has a `Res` interface which lists all the methods that a resource must implement. One method named `Compare`, compares two resources.
To implement this, you'll need to either recommend an alternate design, or use the one provided below.

#### Design:

Currently the Compare signature is:

```
Compare(Res) bool
```

It would be preferable if it was:

```
Cmp(Res) error
```

This way, if the two resources did not compare equally, we'd get an error message why.
You must patch all of the resources to use the new method instead.
If you'd like to do this in stages, your first commit could add a `Cmp` method that just calls `Compare` initially.
Everywhere that `Compare` is currently consumed, also needs to be switched to use `Cmp`, and if errors are propagated, you can use the `errwrap.Wrapf()` pattern if necessary.

Read the contributing tips:
https://github.com/purpleidea/mgmt/blob/master/.github/PULL_REQUEST_TEMPLATE.md

Happy hacking, and ping me for questions!

#### Bonus/Future work:

* Add some tests!

**Comment by purpleidea** [comment]
You'll also want to update these comments: https://github.com/purpleidea/mgmt/blob/master/docs/faq.md#why-do-resources-have-both-a-compare-method-and-an-iff-on-the-uid-method

**Comment by purpleidea** [comment]
Update: the new API has landed. What's left is porting everything from Compare() to Cmp(). This should be a very easy patch. Look in engine/resources/ for what needs changing.

**Comment by purpleidea** [comment]
Patches to remove the `Compare` method from any remaining resources are welcome.

**Comment by dbakong** [comment]
@purpleidea  - PR #544 raised to resolve this issue.

**Comment by purpleidea** [comment]
Merged, so we can close this \o/
