### ISSUE TITLE
File resource on OS X fails

### ISSUE THREAD

**Issue by tuxmea** [purpleidea/mgmt#33]
When managing a file which is not yet available:
- on Linux watcher.Add(current) returns no Error.
- on OS X it returns (*os.PathError)

https://github.com/purpleidea/mgmt/blob/master/file.go#L142

**Comment by purpleidea** [comment]
Assign -> @tuxmea ? ;)

**Comment by tuxmea** [comment]
reported upstream: https://github.com/fsnotify/fsnotify/issues/144

**Comment by purpleidea** [comment]
I think just matching the different error would be fine... I don't know enough about OSX to know if it's a bug.

**Comment by daenney** [comment]
Is this gone? I can't find the relevant code path anymore and I see no references to `watcher.Add` in [file.go](/purpleidea/mgmt/blob/master/resources/file.go). Or does this now apply to the [`Configwatcher.Add()`](/purpleidea/mgmt/blob/master/recwatch/configwatch.go)?

**Comment by purpleidea** [comment]
On Mon, Feb 6, 2017 at 9:13 AM, Daniele Sluijters
<notifications@github.com> wrote:
>
> Is this gone? I can't find the relevant code path anymore and I see no references to watcher.Add in file.go. Or does this now apply to the Configwatcher.Add()?



This code is now in the recwatch/ package. Improvement welcome, but
I'm happy to close this.

**Comment by purpleidea** [comment]
Since nobody is actively stepping up to work on OSX support, and it's not a goal to get us to a minimally viable tool, I'm going to close this for now. Happy to accept OSX patches though.

**Comment by purpleidea** [comment]
One more note: Mgmt would be expected to have this issue on an OSX server (not so common/useful) this shouldn't cause an issue for someone using an OSX machine to talk to their servers.

**Comment by purpleidea** [comment]
Merged in 9544ab2e02418398cb178253b3e05ae44be71374
