### ISSUE TITLE
[DESIGN] Specifying an "undef" equivalent in resources

### ISSUE THREAD

**Issue by purpleidea** [purpleidea/mgmt#333]
What follows is an open design discussion on how we should proceed about specifying the equivalent to `undef` in our resources. Please join in if you have something helpful to contribute. Thanks!

### The problem:

In many tools such as puppet, for a resource, there is the notion of a difference between "no param specified" and "param contains the empty value". The most canonical example is the `file` resource. Two such states exist:

1) file should have contents equal to some string or empty string (zero byte file)
```puppet: file { "/tmp/foo": content => "", }```
2) file contents are not specified (perhaps we're only managing the file mode)
```puppet: file { "/tmp/foo": content => undef, }```

Internally in mgmt this is expressed in the file resource as a:

```
	Content *string `yaml:"content"` // nil to mark as undefined
```
as seen here: https://github.com/purpleidea/mgmt/blob/5f80c1ac2ab6093abcfb7f16157ec0f2eac8fed5/resources/file.go#L52

The `nil` value means "do not manage", where as if the value exists (empty string or otherwise) it means "set contents to that value".

### The status quo in our type system:

We have a robust type system for expressions in our [language](https://purpleidea.com/blog/2018/02/05/mgmt-configuration-language/). A list of types can also be found: https://github.com/purpleidea/mgmt/blob/master/docs/language-guide.md#types

Types are important because they provide safety. It would be difficult or unwise to allow an `undef` argument in the type system, because that would cause this sort of problem:

```
$some_bool = true	# but maybe this value comes from some run-time function like a database lookup

$some_string = if $some_bool {
	"hello"
} else {
	undef	# this "magic" value could cause a problem
}

file "/tmp/foo" {
	content => $some_string,
}
```

At first glance this seems okay, but imagine that the code had something like this:

```
$some_bool = true

$some_string = if $some_bool {
	"hello"
} else {
	undef	# this "magic" value could cause a problem
}

$concat = "blah" + $some_string	# what should happen here?

file "/tmp/foo" {
	content => $concat,
}
```

Now we have a serious problem, because we need to decide what should happen when we try and add a `string` to `undef`. If we decided that that addition should be an error, then the problem is that it would only happen when the `$some_bool` value was true, meaning it would cause a runtime error some of the time, which would cause our programs to fail after they've compiled successfully. This is a property that we'd like to eliminate entirely. If we can eliminate all of the errors at compile time, then our programs will be more robust and we can rely on them for more serious "crash-proof" automation.

### Solving the problem:

One possible solution, is to have a per-resource boolean-input-parameter which specifies whether a parameter should be defined or not. By default if it's not specified, then we would gather that the param should exist, otherwise, we would ignore the param entirely. If we decide that this is the most preferable approach, then the question of syntax comes into play. Here are three possible variants for expressing this syntax:

```
$present = false	# param should not be presend

file "/tmp/option1" {
	($present) ? content => "hello\n",
	mode => "u=rwx,go=rw",
}

file "/tmp/option2" {
	if $present {
		content => "hello\n",
	}
	mode => "u=rwx,go=rw",
}

file "/tmp/option3" {
	($present) content => "hello\n",
	mode => "u=rwx,go=rw",
}

file "/tmp/option4" {
	content => $present ?: "hello\n",	# should the bool be inverted here?
	mode => "u=rwx,go=rw",
}
```

None of these are currently implemented in the language, but they are presented early for discussion.

### Your mission should you choose to accept it:

1) If you like this approach but have an alternate syntax for accomplishing this, then please leave a comment with an example of the syntax that you've invented. You're welcome to change anything you like in the existing syntax to accomplish this. If it's a better idea, we'll use it.

2) If there's a better approach entirely to describing this `undef` vs. "empty value" problem, then please let us know!

### Related problems:

1) "Default values": A simpler subset of this problem is one of specifying the "default value" for a particular param. If we have a way to `undef` a parameter, then omitting it that way is a simple way to cause the default value to be used. If it turns out that we want to actually *know* those values, then it would be relatively easy to export a `const.res.file.mode` type variable which contains the default value for the mode for the file resource. Other constants could also be exported.

2) Inline resource edges (dependencies): A similar issue exists when specifying dependencies between resources. This will be discussed in another issue.

**Comment by purpleidea** [comment]
haha, I agree, we *aren't* adding a `null` :)

> would be a special construct, yes?

Yes, to clarify, all of the "Solving the problem" options were meant as special syntax. IOW, if we used the `if` inside a resource, that's actually just special syntax as part of the resource in the parser, not arbitrary constructs. Similarly the "elvis operator" variant (option 4) would also be a special inside-resources-construct as well.

> optional types

A fancier type system might be a good approach long term, but it's way out of scope for v1.0. We can look at this when there are more eyes on the language.

> Ansible has a special constant called omit

As far as I can tell this seems to be a special value along the lines of `undef`, so in that regard, I'm going to pass over this idea unless someone can explain it better...

So at the moment, based on your reply, did I understand correctly that my best option looks like:

```
file "/tmp/option4" {
	content => $present ?: "hello\n",	# should the bool be inverted here?
	mode => "u=rwx,go=rw",
}
```
Let me know what you think, and what the default state of the $present should be.

Thanks!

**Comment by roidelapluie** [comment]
Why don't we just imitate go and say that there is no undef value, just "zero" values?

**Comment by purpleidea** [comment]
> Why don't we just imitate go and say that there is no undef value, just "zero" values?

The problem is that for some parameters there is a distinction in behaviour, eg for file:

content => "" # empty string means contents should be empty

vs

missing content, means don't touch the file contents (maybe we're only changing the mode)

**Comment by purpleidea** [comment]
Here's an initial implementation of the fourth option (the `elvis` operator): https://github.com/purpleidea/mgmt/tree/feat/elvis

I'm tempted to merge this unless there's more discussion to be had. Also happy to reconsider and change the design if there's a better solution.

@ffrank I am a bit ashamed I didn't include a test with the patch, but I did add docs! \o/

**Comment by ffrank** [comment]
Looks like a fair compromise to me.

**Comment by purpleidea** [comment]
BTW, most of this is merged in master. I'll leave this open for now until the `default values` issue is solved.

**Comment by purpleidea** [comment]
This is done with the elvis operator, and the default values stuff is mentioned in #579
