### ISSUE TITLE
[Discuss] Should we move to golang 1.9 and etcd 3.3 ?

### ISSUE THREAD

**Issue by purpleidea** [purpleidea/mgmt#334]
See here:

https://www.redhat.com/archives/mgmtconfig-list/2018-February/msg00000.html

If no major objections I'll be pushing this through shortly.

**Comment by jcftang** [comment]
+1 on upping the dependency to something recent

**Comment by purpleidea** [comment]
Patch cooking here...
https://github.com/purpleidea/mgmt/tree/feat/bump-etcd

**Comment by purpleidea** [comment]
Done in git master.
