### ISSUE TITLE
time package requirement

### ISSUE THREAD

**Issue by logicminds** [purpleidea/mgmt#336]
## Versions:

* mgmt version (eg: `mgmt --version`):
0.0.14-30-ge3a2648
* operating system/distribution (eg: `uname -a`):
Docker image: golang:latest
* golang version (eg: `go version`):
1.9.4
## Description:
Followed the steps from the getting started doc.  Ran into this issue

https://github.com/purpleidea/mgmt/blob/master/docs/quick-start-guide.md#setting-up-golang

```
root@21b4f89f024e:/go/src/github.com/purpleidea/mgmt# make build
Generating: bindata...
Generating: lang...
make --quiet -C lang
Building: mgmt, os/arch: linux-amd64, version: 0.0.14-30-ge3a2648...
env GOOS=linux GOARCH=amd64 time go build -i -ldflags "-X main.program=mgmt -X main.version=0.0.14-30-ge3a2648 -s -w" -o build/mgmt-linux-amd64 ;
env: 'time': No such file or directory
Makefile:143: recipe for target 'build/mgmt-linux-amd64' failed
make: *** [build/mgmt-linux-amd64] Error 127
root@21b4f89f024e:/go/src/github.com/purpleidea/mgmt#
```

**Comment by purpleidea** [comment]
@logicminds Oh wow. You don't have the `time` package installed. Can you install it?

**Comment by logicminds** [comment]
yup.  Submitting PR too.

**Comment by logicminds** [comment]
Was this fixed?

**Comment by purpleidea** [comment]
Yup
