### ISSUE TITLE
DEPRECATED Action signature

### ISSUE THREAD

**Issue by tuxmea** [purpleidea/mgmt#34]
mgmt finishes with the following deprecation warning:
DEPRECATED Action signature.  Must be `cli.ActionFunc`.  This is an error in the application.  Please contact the distributor of this application if this is not you.  See https://github.com/codegangsta/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature

**Comment by purpleidea** [comment]
@tuxmea Cool, didn't know this... I probably haven't updated my cli lib lately.

**Comment by purpleidea** [comment]
Thanks for the report. Fixed in git master.
