### ISSUE TITLE
make deps issues

### ISSUE THREAD

**Issue by ofrzeta** [purpleidea/mgmt#344]
## Versions:

* operating system/distribution (eg: `uname -a`):

CentOS 7

* golang version (eg: `go version`):

Go 1.10

## Description:

Building mgmt according to the Quickstart fails with the following error messages during "make dep":

```
running 'go get -v -d ./...' from /home/oliver/go/src/github.com/purpleidea/mgmt
lib/cli.go:28:2: no buildable Go source files in 
/home/oliver/go/src/github.com/purpleidea/mgmt/bindata
done running 'go get -v -t -d ./...'
dirname: missing operand
Try 'dirname --help' for more information.
dirname: missing operand
Try 'dirname --help' for more information.
mv: cannot stat '/gometalinter.v1': No such file or directory
```

Also I noticed that "make dep" downgrades my Go installation because it installs the distribution package (same on Ubuntu 16.04).

**Comment by purpleidea** [comment]
@ofrzeta This is a common bug, we need to patch. The rest of the deps should have been installed correctly. I think if you have $GOBIN in your path, then you don't hit this bug.

Other than that, sorry we installed a golang version! I would recommend writing a patch that checks for an existing golang of a sufficient version before installing if you'd be interested!

Thanks for the report.

**Comment by ofrzeta** [comment]
The build doesn't work, though, because "go-bindata" can't be found. I will try to look into the makedeps problem and report later.

**Comment by purpleidea** [comment]
@ofrzeta Ah! The `misc/make-deps.sh` has been an excellent learning experience about environments that it doesn't work in. Sorry about that. You can fix that by running this line:

https://github.com/purpleidea/mgmt/blob/master/misc/make-deps.sh#L94

I'm going to close this issue for now, but if you have any ways to improve the script, so that it would be more robust to your environment, please send a patch.

Thanks!

**Comment by adamsigal** [comment]
> @ofrzeta This is a common bug, we need to patch. The rest of the deps should have been installed correctly. I think if you have $GOBIN in your path, then you don't hit this bug.
> 
> Other than that, sorry we installed a golang version! I would recommend writing a patch that checks for an existing golang of a sufficient version before installing if you'd be interested!
> 
> Thanks for the report.

I'd like to write a patch for this when I get back up and running. It has been an issue over my various mgmt installations.

**Comment by purpleidea** [comment]
@adamsigal I think it just has to do with your golang env being setup wrong or missing the $GOBIN. Maybe the distro packages could add this automatically with an /etc/profile.d/ script for the golang package.

**Comment by adamsigal** [comment]
The problem I was referring to was even if you have a newer golang version insalled, make deps installs golang from the package manager. In the case of Ubuntu, this is currently golang version 10.x. Later in the script, if your golang version is lower than 11.x the script exits. So make deps shoots itself in the foot in these cases.

**Comment by purpleidea** [comment]
@adamsigal If this happens, maybe the script should just print a friendly error message before it dies?

**Comment by adamsigal** [comment]
@purpleidea I think, most importantly, that if a sufficiently recent golang version is already installed on the machine the script shouldn't install golang again. That's the root of the problem.

**Comment by purpleidea** [comment]
Add a patch that checks for `go version`, and if it's okay, skips the installation?

**Comment by adamsigal** [comment]
Exactly! I'll get on it once i get my installation sorted out.
