### ISSUE TITLE
Emacs support for language

### ISSUE THREAD

**Issue by mavit** [purpleidea/mgmt#348]
I've prepared rudimentary Emacs support for the mgmt language, at https://github.com/mavit/mgmt-mode.

Would you like to import this into the mgmt Git repository, or keep it separate?  Once a URL for it is settled, I can prepare a recipe to incorporate it into the Emacs package repository at https://melpa.org/.

**Comment by purpleidea** [comment]
@mavit Oh wow!

Thank you!

This has been on my TODO list for as long as I knew I needed to build a language! See: https://github.com/purpleidea/mgmt/blob/master/TODO.md#language-improvements

I would love to have this upstream here, maybe you could recommend where it should go? Perhaps an `emacs/` directory or `misc/emacs/` ? Alternate suggestions are welcome.

My only thought would be to consider naming it `mgmtconfig-mode` to make it less ambiguous if you think that would be an issue.

Thank you again!

**Comment by mavit** [comment]
Lets go with `misc/emacs/`, assuming that there'll be a `misc/vim/` in future.

I must admit I found the branding a bit muddled: sometimes "mgmt", sometimes "mgmtconfig".  Happy to rename to `mgmtconfig-mode` if that's preferred by you.

I'll prepare a pull request.

**Comment by purpleidea** [comment]
Since the initial commit is merged, I am going to close this, but future patches/improvements are certainly welcome!

We just added edge support, and I also noticed that a few of the entries you added from resources/*.go are not actually resources.

Thanks again!
