### ISSUE TITLE
[bug] CLI fails after recompile

### ISSUE THREAD

**Issue by jonathangold** [purpleidea/mgmt#390]
## Versions:

* mgmt version (eg: `mgmt --version`):
`0.0.15-33-g9ea5c03`

* operating system/distribution (eg: `uname -a`):
`Linux localhost.localdomain 4.16.5-300.fc28.x86_64 #1 SMP Fri Apr 27 17:38:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

* golang version (eg: `go version`):
`go version go1.10.1 linux/amd64`

## Description:
When I recompile and run mgmt it fails, telling me to check the Makefile. 
```
jon@localhost ~/mgmt $ make clean
jon@localhost ~/mgmt $ make build
Generating: bindata...
Generating: lang...
make --quiet -C lang
Building: mgmt, os/arch: linux-amd64, version: 0.0.15-33-g9ea5c03...
time env GOOS=linux GOARCH=amd64 go build -i -ldflags "-X main.program=mgmt -X main.version=0.0.15-33-g9ea5c03 -s -w " -o build/mgmt-linux-amd64 ;

real    0m3.382s
user    0m3.888s
sys     0m0.591s
cp -a build/mgmt-linux-amd64 mgmt
jon@localhost ~/mgmt $ ./mgmt
program was not compiled correctly, see Makefile
```
It fails because `Cli()` isn't getting the arguments it wants here. https://github.com/purpleidea/mgmt/blob/996928622406158b18b7883a6645e224409005f3/lib/cli.go#L201

`make run` works fine since it gets the variables from the Makefile itself.

I found this, but I'm not sure how that works. https://github.com/purpleidea/mgmt/blob/996928622406158b18b7883a6645e224409005f3/main.go#L34

**Comment by jonathangold** [comment]
If I wipe my directory and re-clone, it works, albeit temporarily (possibly until I switch branches, but will have to test to confirm.)

**Comment by jonathangold** [comment]
@purpleidea I know you're env is almost identical to mine. Have you hit this issue?

**Comment by purpleidea** [comment]
Those two vars are set here: https://github.com/purpleidea/mgmt/blob/master/Makefile#L145

If you're experiencing this issue, make sure you're using `make build` and not `go build` and it should work.

Otherwise maybe something changed in 1.10 ??

**Comment by jonathangold** [comment]
> Otherwise maybe something changed in 1.10 ??
I think that must be the case, unless something else about my env isn't set up right. As you can see in my original post, I used `make build` after `make clean`

I'll investigate further later today.

**Comment by jonathangold** [comment]
https://github.com/golang/go/issues/24310 seems to be related

**Comment by jonathangold** [comment]
@purpleidea after some playing around, I figured out that `-ldflags "-X...` needs to be replaced with `-ldflags=github.com/purpleidea/mgmt="-X...` Trying to figure out a clean way to have both versions in the Makefile, since 1.9 won't compile properly with the change, before I send a patch.

**Comment by purpleidea** [comment]
@jonathangold Nice find! Good thing golang never breaks api ;)

**Comment by purpleidea** [comment]
(I think previously we just did an if statement in the makefile using the output of `go version`) -- There might be an old variant of this in the git log when we moved to the newer golang version that handled ldflags differently.)

**Comment by jonathangold** [comment]
@purpleidea Cool. I'll pick it up again in a few hours. That's what I figured would be needed (plus `PKGNAME := $(shell go list .)` to get the package name

**Comment by purpleidea** [comment]
@jonathangold In case it saves you time, the old way we did this is here: 08d5a3baaeff470ad1580ce920b078b132a5a688

Thanks for looking into this! :)

**Comment by jonathangold** [comment]
I just found it. :) Should have looked here first :P Opening PR shortly.
