### ISSUE TITLE
What is it with deltaDepth...I mean seriously

### ISSUE THREAD

**Issue by ffrank** [purpleidea/mgmt#42]
;-)

I've stumbled multiple times reading this. It's 3AM now, so this might not be the best time to finally bring this up, but I'm almost certain something is wrong here.

Consider [these four lines](https://github.com/purpleidea/mgmt/blob/6bbce039aa6ac7b1fa9ea617663e7ad6b5a5cffa/file.go#L175-L179). To put it into words: if the path that raised an event has the currently focused path as a prefix, then subtract the length of the event path from that prefix. Otherwise, if the current focus has the event path as a prefix, subtract the length of the focus path from its prefix.

In both cases, the length of the longer path is subtracted. Each will yield a value below zero. So what's going on? I suppose this is a bug, but my mind boggles whenever I try and trace its implications. Halp!

**Comment by purpleidea** [comment]
From here: https://github.com/purpleidea/mgmt/blob/6bbce039aa6ac7b1fa9ea617663e7ad6b5a5cffa/file.go#L169

> the deeper you go, the bigger the deltaDepth is...
> this is the difference between what we're watching,
> and the event... doesn't mean we can't watch deeper

This means, IOW, it's the difference between where our current watch is, and what the event is. It probably has limited (but important usefulness) in the current implementation, but I fully expected it to be quite crucial when writing the recursive extension to this.

**Comment by ffrank** [comment]
Removed some late-night cruft from the original post.

Could you look at the piece of logic I linked? It looks broken to me.

**Comment by purpleidea** [comment]
@ffrank I looked at it, and I don't think it's broken. Look at it this way, I've used this code extensively, and it seems to work perfectly...

**Comment by purpleidea** [comment]
Alternatively, feel free to rewrite whatever you want, whether or not it works and then gets merged is a different question.

**Comment by ffrank** [comment]
Any help would be appreciated. Have you ever observed a positive deltaDepth value?

I've been struggling last night to come up with proper behavior wrt. watched subdirectory trees. Confused by the maths. It might well be that some code paths are currently unreachable (and unnecessary), but we may need them once watches descend into subdirectories. Any extra insight will go a long way.

**Comment by purpleidea** [comment]
On Wed, May 18, 2016 at 9:04 AM, Felix Frank <notifications@github.com>
wrote:

> Any help would be appreciated. Have you ever observed a positive
> deltaDepth value?
>
> I've been struggling last night to come up with proper behavior wrt.
> watched subdirectory trees. Confused by the maths. It might well be that
> some code paths are currently unreachable (and unnecessary), but we may
> need them once watches descend into subdirectories. Any extra insight will
> go a long way.
>

Right now, the event will always happen at the "current" directory or
HIGHER. (deltadepth) Once we have recursive directories, the event could
also happen INSIDE that directory. (deltadepth of opposite sign)
