### ISSUE TITLE
Github license

### ISSUE THREAD

**Issue by pierreozoux** [purpleidea/mgmt#426]
Just a quick note, your license is not recognize by Github, so at first it looks like a proprietary project.

Thanks for your work!

**Comment by purpleidea** [comment]
Sorry for that! I did know, however there's not much I can do. I think GH uses two different libs to decide what to display. One of which is https://github.com/benbalter/licensee IIRC. If you'd like to run that on the repo (on your computer) and then fix any bugs so it works (upstream in that project), that would be awesome! Can't do anything to fix on my side unfortunately, unless there's some .github/license metadata key I don't know about :(

Thanks for your interest in the project!! Send us patches or patreon support so we can keep it not proprietary! https://www.patreon.com/purpleidea
