### ISSUE TITLE
implement a DHCPv4 resource

### ISSUE THREAD

**Issue by jonathangold** [purpleidea/mgmt#427]
This resource would listen and serve DHCP traffic. Here's an idea of what the api might look like in use:

```
dhcp "foo" {
    range => {"192.168.1.100", "192.168.1.200",},
    subnetmask => "255.255.255.0",
    routers => {"192.168.1.1",},
    domainsearch => {"foo.com", "bar.net",},
    dnsservers => {"192.168.1.2", "192.168.1.3",},
    reservations => {
        {"09-87-65-43-21-09", "192.168.1.100",}, 
        {"01-23-45-67-89-01", "192.168.1.101",},
    }, 
}
```
To make this work, the `Watch()` loop will need to listen for dhcp requests, and probably store incoming connections in a private struct field. Then `CheckApply()` can iterate through all the connections and serve each one. 

Comments?

**Comment by purpleidea** [comment]
> dhcp "foo" {

dhcp or dhcpd?
Also, what does the name represent?

>    range => {"192.168.1.100", "192.168.1.200",},
What structure is this?

    subnetmask => "255.255.255.0",
> I'd like to use /cidr instead of masks if possible. Masks are supposed to be deprecated.

>    routers => {"192.168.1.1",},
LGTM, let's call this routes or route

    domainsearch => {"foo.com", "bar.net",},
> search

    dnsservers => {"192.168.1.2", "192.168.1.3",},
> dns

    reservations => {
        {"09-87-65-43-21-09", "192.168.1.100",}, 
        {"01-23-45-67-89-01", "192.168.1.101",},
on linux we use colons ;)

    }, 
}

But what are these datastructures you're using?

**Comment by purpleidea** [comment]
> But what are these datastructures you're using?

You're making me think we need to add a tuple :P

**Comment by jonathangold** [comment]
> But what are these datastructures you're using?
Was thinking `[]string{}`, but tuples would so much better! Could also use a struct, like we would in golang.

**Comment by purpleidea** [comment]
> Was thinking []string{}

That's golang. This is `mcl`. ;)

> but tuples would so much better! Could also use a struct, like we would in golang.

Yeah, you probably want a struct for some of those. And when I said tuple, I really meant struct, but without key names.

**Comment by purpleidea** [comment]
Probably a plan for a future day.

**Comment by jonathangold** [comment]
> That's golang. This is mcl. ;)

fair enough (I'm also thinking about implementation". I guess the mcl version is "list of strings",

**Comment by purpleidea** [comment]
As a small note, I implemented an easier first resource, a TFTP server, which works great so far.

The rough design could be copied for DHCP. I started looking into DHCP and have some initial code. If someone wants to continue this, lmk. The only bugs in TFTP are: https://github.com/purpleidea/mgmt/issues/577 and also I think part of the TFTP lib blocks on some timeouts. (Need to add a context.)

**Comment by purpleidea** [comment]
I forgot to mention it earlier, but there is a working dhcp resource (server) merged now. Look in `examples/lang/dhcp0.mcl` for more info.
