### ISSUE TITLE
Surpring double evaluation of valid resource state in noop mode

### ISSUE THREAD

**Issue by ncharles** [purpleidea/mgmt#477]
Consider the following code

`file "/etc/drbd.conf" {
  content => "this is an mgmt test",
  state => "exists",
  Meta:noop => true,
}
file "/tmp/bla" {
  Depend => File["/etc/drbd.conf"],
  content => "some content",
}`

If /etc/drdb.conf is valid, and we mess with /tmp/bla, we get the following output

> 15:50:00 main.go:414: engine: file[/etc/drbd.conf]: CheckApply(false)
15:50:00 main.go:414: engine: file[/etc/drbd.conf]: resource: contentCheckApply(false)
15:50:00 main.go:414: engine: file[/etc/drbd.conf]: resource: chmodCheckApply(false)
15:50:00 main.go:414: engine: file[/etc/drbd.conf]: resource: chownCheckApply(false)
15:50:00 main.go:414: engine: file[/etc/drbd.conf]: CheckApply(false): Return(true, <nil>)
15:50:00 main.go:414: engine: file[/tmp/bla]: CheckApply(true)
15:50:00 main.go:414: engine: file[/tmp/bla]: resource: contentCheckApply(true)
15:50:00 main.go:414: engine: file[/tmp/bla]: resource: chmodCheckApply(true)
15:50:00 main.go:414: engine: file[/tmp/bla]: resource: chownCheckApply(true)
15:50:00 main.go:414: engine: file[/tmp/bla]: CheckApply(true): Return(false, <nil>)
15:50:00 main.go:414: engine: file[/etc/drbd.conf]: CheckApply(false)
15:50:00 main.go:414: engine: file[/etc/drbd.conf]: resource: contentCheckApply(false)
15:50:00 main.go:414: engine: file[/etc/drbd.conf]: resource: chmodCheckApply(false)
15:50:00 main.go:414: engine: file[/etc/drbd.conf]: resource: chownCheckApply(false)
15:50:00 main.go:414: engine: file[/etc/drbd.conf]: CheckApply(false): Return(true, <nil>)

I would expect that the drdb would be checked only once

**Comment by ncharles** [comment]
If both are in Noop, then the output is what I would expect

> 15:54:10 main.go:414: engine: file[/etc/drbd.conf]: CheckApply(false)
15:54:10 main.go:414: engine: file[/etc/drbd.conf]: resource: contentCheckApply(false)
15:54:10 main.go:414: engine: file[/etc/drbd.conf]: resource: chmodCheckApply(false)
15:54:10 main.go:414: engine: file[/etc/drbd.conf]: resource: chownCheckApply(false)
15:54:10 main.go:414: engine: file[/etc/drbd.conf]: CheckApply(false): Return(true, <nil>)
15:54:10 main.go:414: engine: file[/tmp/bla]: CheckApply(false)
15:54:10 main.go:414: engine: file[/tmp/bla]: resource: contentCheckApply(false)
15:54:10 main.go:414: engine: file[/tmp/bla]: resource: chmodCheckApply(false)
15:54:10 main.go:414: engine: file[/tmp/bla]: resource: chownCheckApply(false)
15:54:10 main.go:414: engine: file[/tmp/bla]: CheckApply(false): Return(false, <nil>)

**Comment by ncharles** [comment]
Sometimes, editing /tmp/bla results in following log

> 16:06:15 main.go:414: engine: file[/etc/drbd.conf]: CheckApply(false)
16:06:15 main.go:414: engine: file[/etc/drbd.conf]: resource: contentCheckApply(false)
16:06:15 main.go:414: engine: file[/etc/drbd.conf]: resource: chmodCheckApply(false)
16:06:15 main.go:414: engine: file[/etc/drbd.conf]: resource: chownCheckApply(false)
16:06:15 main.go:414: engine: file[/etc/drbd.conf]: CheckApply(false): Return(true, <nil>)
16:06:15 main.go:414: engine: file[/tmp/bla]: CheckApply(true)
16:06:15 main.go:414: engine: file[/tmp/bla]: resource: contentCheckApply(true)
16:06:15 main.go:414: engine: file[/tmp/bla]: resource: chmodCheckApply(true)
16:06:15 main.go:414: engine: file[/tmp/bla]: resource: chownCheckApply(true)
16:06:15 main.go:414: engine: file[/tmp/bla]: CheckApply(true): Return(false, <nil>)
16:06:15 main.go:414: engine: file[/etc/drbd.conf]: CheckApply(false)
16:06:15 main.go:414: engine: file[/etc/drbd.conf]: resource: contentCheckApply(false)
16:06:15 main.go:414: engine: file[/etc/drbd.conf]: resource: chmodCheckApply(false)
16:06:15 main.go:414: engine: file[/etc/drbd.conf]: resource: chownCheckApply(false)
16:06:15 main.go:414: engine: file[/etc/drbd.conf]: CheckApply(false): Return(true, <nil>)
16:06:15 main.go:414: engine: file[/tmp/bla]: CheckApply(true)
16:06:15 main.go:414: engine: file[/tmp/bla]: resource: contentCheckApply(true)
16:06:15 main.go:414: engine: file[/tmp/bla]: resource: chmodCheckApply(true)
16:06:15 main.go:414: engine: file[/tmp/bla]: resource: chownCheckApply(true)
16:06:15 main.go:414: engine: file[/tmp/bla]: CheckApply(true): Return(true, <nil>)

so a recheck on /tmp/bla compared to output on first message

**Comment by purpleidea** [comment]
So we just discussed this in person and everything seems to be as expected.

**Comment by ncharles** [comment]
Awesome, thank for the explanations
