### ISSUE TITLE
file resource errs when content is empty and state => "exists"

### ISSUE THREAD

**Issue by ncharles** [purpleidea/mgmt#480]
## Versions:

* mgmt version (eg: `mgmt --version`): mgmt version 0.0.18-5-g94c4090-dirty

* operating system/distribution (eg: `uname -a`): Linux server 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u3 (2017-08-06) x86_64 GNU/Linux

* golang version (eg: `go version`): go version go1.12 linux/amd64

## Description:

file "/tmp/mgmt-elvis" {
  state => "exists",
}
errs with

> 17:23:04 main.go:414: engine: file[/tmp/mgmt-elvis]: SendRecv: map[]
17:23:04 main.go:414: engine: file[/tmp/mgmt-elvis]: CheckApply(true)
17:23:04 main.go:414: engine: file[/tmp/mgmt-elvis]: resource: contentCheckApply(true)
17:23:04 main.go:414: engine: file[/tmp/mgmt-elvis]: resource: chmodCheckApply(true)
17:23:04 main.go:414: engine: file[/tmp/mgmt-elvis]: resource: chownCheckApply(true)
17:23:04 main.go:414: engine: file[/tmp/mgmt-elvis]: CheckApply(true): Return(false, stat /tmp/mgmt-elvis: no such file or directory)
17:23:04 main.go:414: engine: file[/tmp/mgmt-elvis]: converger: reset timer
17:23:04 main.go:414: engine: Process(file[/tmp/mgmt-elvis]): Return(stat /tmp/mgmt-elvis: no such file or directory
error during Process()
github.com/purpleidea/mgmt/engine/graph.(*Engine).Process
	/root/gopath/src/github.com/purpleidea/mgmt/engine/graph/actions.go:239
github.com/purpleidea/mgmt/engine/graph.(*Engine).Worker
	/root/gopath/src/github.com/purpleidea/mgmt/engine/graph/actions.go:523
github.com/purpleidea/mgmt/engine/graph.(*Engine).Commit.func1.2.1
	/root/gopath/src/github.com/purpleidea/mgmt/engine/graph/engine.go:209
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1337)
17:23:04 main.go:414: engine: Watch(file[/tmp/mgmt-elvis]): Exited(<nil>)
17:23:04 main.go:414: engine: Worker(file[/tmp/mgmt-elvis]): Exited(1 error occurred:
	* error during Process(): stat /tmp/mgmt-elvis: no such file or directory

**Comment by purpleidea** [comment]
This is now fixed in https://github.com/purpleidea/mgmt/commit/426b15313e451332829677ae6e37bacacae3cbdc

And there is also a test.

**Comment by ncharles** [comment]
thank you !
