### ISSUE TITLE
[LOVE] State directory with xdg dirs

### ISSUE THREAD

**Issue by purpleidea** [purpleidea/mgmt#498]
This is a beginner level golang patch for someone who is interested in getting involved.

We should consider having our default `/var/lib/mgmt/` dir be a combination of https://github.com/systemd/portable-walkthrough-go/blob/5f2b36a0f2ce30325119224956c837d43fa6782e/main.go#L34 (systemd's STATE_DIRECTORY env var) and xdg dirs when that is not specified.

You'll need to see where that initial path comes from, and add the logic to implement the above.

Anyone interested in writing the patch, please let us know here!

**Comment by hooksie1** [comment]
Are you thinking the xdg dir should be XDG_CONFIG_HOME or something different?

**Comment by purpleidea** [comment]
I think the state part should probably go in `~/.cache/` which is XDG_CACHE_HOME. (Better suggestions welcome if I'm interpreting XDG spec wrong.)

Of course this is all secondary to if the systemd STATE_DIRECTORY is not present.

@hooksie1 Want to write a patch?

**Comment by hooksie1** [comment]
Ok yeah I think you're right, that makes more sense. I might give it a shot and see what terrible thing I can come up with.

**Comment by purpleidea** [comment]
@hooksie1 Okay awesome! Join us in #mgmtconfig on Freenode IRC for questions, and feel free to send an early (even broken) PR/patch for early review.

Cheers!

**Comment by hooksie1** [comment]
PR #530 is in.

**Comment by purpleidea** [comment]
Merged!
