### ISSUE TITLE
Build doesn't check for old golang

### ISSUE THREAD

**Issue by jerith** [purpleidea/mgmt#51]
I tried to build `mgmt` using the default golang in debian jessie, which I later realised is 1.3.3. It would be helpful for the build scripts to check the golang version and exit with a useful message if it's too old.

**Comment by purpleidea** [comment]
+1

**Comment by purpleidea** [comment]
Should I leave this patch to you?

**Comment by jerith** [comment]
Sure. I'll poke around when I have some time.
