### ISSUE TITLE
impossible to escape ${test}

### ISSUE THREAD

**Issue by roidelapluie** [purpleidea/mgmt#521]
## Versions:

* mgmt version (eg: `mgmt --version`): master

* operating system/distribution (eg: `uname -a`): linux 5.1.1

* golang version (eg: `go version`): 1.12

## Description:

The following mcl code fails

```
print "\${test}" {}
```
2019-05-15 14:47:47.045206 I | run: error: cli parse error: could not generate AST: string: bad escaping: `"\${test}"` @2:7

**Comment by purpleidea** [comment]
@roiedelapluie

Very interesting, however I'm not sure this is a bug... This is the equivalent of doing:

```mcl

print "\HELLO" {}

```

Which would error because the backslash is missing a valid escape char or a friend.
Instead use:

```mcl
print "$" + "{test}" {}
```

I'm not sure there's another way, since `${XXX}` is meant as a special way to get a special var forced.

What do you think? NOTABUG?

**Comment by roidelapluie** [comment]
It is a bug.

**Comment by roidelapluie** [comment]
escaping is escaping

**Comment by purpleidea** [comment]
If you think it's a bug, could you submit it upstream here: https://github.com/hashicorp/hil

and see what they say. That's the lib we use.

**Comment by purpleidea** [comment]
I think actually that the bug is in my code...

**Comment by purpleidea** [comment]
Unquote/UnquoteChar doesn't know about $ because it's golang. We might have to copy the functions in, and add them. But we have to think about what we pass through. I guess `\$` would need to cause `\$` to be passed through to hil.
https://golang.org/src/strconv/quote.go?s=9955:9993#L347

**Comment by purpleidea** [comment]
(Or maybe we should modify Unquote to not deal with escape removal-- we could do that in hil instead AIUI.

**Comment by purpleidea** [comment]
Seems this has two components to it:

1) Getting through strconv.Unquote

2) Getting through hashicorp's hil

Neither obey escaping of $ (the first shouldn't, but the second should I think)

I've patched part 1 of this in the `Unquote` side. (Not in git master yet.)

Part two is https://github.com/hashicorp/hcl/issues/341

**Comment by apparentlymart** [comment]
The escape sequence for a HIL interpolation marker is `$${`, not `\${`. (When using HIL inside HCL 1, backslashes are escapes for HCL itself, not for HIL.)

**Comment by purpleidea** [comment]
@apparentlymart That is very helpful information, thank you.

I'll be digging into the code to try and port it to the standard escape sequence, and this will probably end up as a fork. In the odd chance you can point me to the right place in the code to patch this, it's appreciated!

Thank you!

**Comment by purpleidea** [comment]
I think I've got a fix for this. No need to dig into the code. Thanks!

**Comment by purpleidea** [comment]
This is fixed now. If you have other issues, please submit a short test example. Thanks!
