### ISSUE TITLE
Fedora 30 

### ISSUE THREAD

**Issue by hooksie1** [purpleidea/mgmt#528]
## Versions:

* mgmt version (eg: `mgmt --version`): 0.0.19-1

* operating system/distribution (eg: `uname -a`): Fedora 30 (Workstation & Cloud)

* golang version (eg: `go version`): 1.12.5

## Description:

Cloned the repo and downloaded the release from the releases page. Ran the example with hello0.mcl and I get this output:

```
[vagrant@localhost bin]$ ./mgmt run --tmp-prefix lang ~/gopath/src/github.com/purpleidea/mgmt/examples/lang/hello0.mcl 
2019-06-28 23:54:51.063393 I | main: no frontend selected (no GAPI activated)
This is: mgmt, version: 0.0.19
Copyright (C) 2013-2019+ James Shubin and the project contributors
Written by James Shubin <james@shubin.ca> and the project contributors
23:54:51 main: start: 1561766091063811042
23:54:51 main: warning: working prefix directory is temporary!
23:54:51 main: working prefix is: /tmp/mgmt-localhost.localdomain-917625550
23:54:51 PGP: Created key: 4F0762CD
23:54:51 main: no seeds specified!
23:54:51 etcd: running...
23:54:51 etcd: watching chooser...
23:54:51 etcd: bootstrapping...
23:54:51 etcd: nominated: localhost.localdomain=http://localhost:2380
23:54:51 etcd: waiting for server...
23:54:51 etcd: server: runServer: (newCluster=true): localhost.localdomain=http://localhost:2380
23:54:51 etcd: server: starting...
23:54:52 etcd: server: ready
23:54:52 etcd: connect...
23:54:52 etcd: connected!
23:54:52 etcd: chooser: set dynamic cluster size to: 5
23:54:52 etcd: watching nominees...
23:54:52 etcd: nominated: localhost.localdomain=http://localhost:2380
23:54:52 etcd: watching volunteers...
23:54:52 etcd: volunteering...
23:54:52 etcd: volunteers: localhost.localdomain=http://localhost:2380
23:54:52 etcd: chooser: (localhost.localdomain=http://localhost:2380)/(localhost.localdomain=http://localhost:2380)
23:54:52 etcd: chooser result(+/-): []/[]
23:54:52 etcd: watching endpoints...
23:54:52 main: etcd is ready!
23:54:52 main: waiting...
23:54:52 etcd: volunteers: localhost.localdomain=http://localhost:2380
23:54:52 etcd: chooser: (localhost.localdomain=http://localhost:2380)/(localhost.localdomain=http://localhost:2380)
23:54:52 etcd: chooser result(+/-): []/[]
23:54:52 main: running...
23:54:52 main: deploy: empty
23:54:52 main: waiting...
23:54:52 gapi: generating empty graph...
23:54:52 engine: autoedge: adding autoedges...
23:54:52 engine: autogroup: algorithm: wrappedGrouper: NonReachabilityGrouper...
23:54:52 main: commit...
23:54:52 engine: graph sync...
23:54:52 main: graph: Vertices(0), Edges(0)
23:54:52 main: waiting...
23:54:52 main: waiting...

```

Seems to be running? But doesn't create /tmp/mgmt-hello-world. Used the Vagrant box fedora/30-cloud-base and it worked fine when doing a make clean build, however the downloadable release tarball doesn't work.

**Comment by purpleidea** [comment]
@hooksie1 The issue is here:

```
[vagrant@localhost bin]$ ./mgmt run --tmp-prefix lang ~/gopath/src/github.com/purpleidea/mgmt/examples/lang/hello0.mcl 
2019-06-28 23:54:51.063393 I | main: no frontend selected (no GAPI activated)
```

In the release tarball you need to add `--lang` after `lang` which was weird, and is removed in git master (where the docs are)

So either move to git master or add `--lang` for now.

Sorry about that, I should hopefully do a new release soonish.

**Comment by hooksie1** [comment]
Oh ok. I must have missed that somehow. Thanks!

**Comment by purpleidea** [comment]
On Fri, Jun 28, 2019 at 8:12 PM John Hooks <notifications@github.com> wrote:
>
> Oh ok. I must have missed that somehow. Thanks!

Not your fault, just a consequence of you being unlucky and hitting
the window between releases where the docs are out of sync. Sorry
about that! The more stable we get the less likely of breaking changes
like this.

Let us know if we can help you get involved with coding, or if you'd
like to donate to the project!

**Comment by hooksie1** [comment]
I'd possibly like to get involved. I do a ton with Ansible and I like Go a lot. I come from an ops background so I'm trying to get better at development, so this might be a good way to get more experience.

**Comment by purpleidea** [comment]
On Fri, Jun 28, 2019 at 8:22 PM John Hooks <notifications@github.com> wrote:
>
> I'd possibly like to get involved. I do a ton with Ansible and I like Go a lot. I come from an ops background so I'm trying to get better at development, so this might be a good way to get more experience.

We're happy to mentor your patches. Join us in #mgmtconfig on Freenode
IRC. Ping me in there and we can help you get going with a first patch
that fits your experience and interest.

Cheers!
