### ISSUE TITLE
Feedback: Tutorial for absolute noobs like me

### ISSUE THREAD

**Issue by avierr** [purpleidea/mgmt#531]
Some honest feedback here,
When I go through mgmt I tried hard to figure out what this really is:
Initially articles make it looks like some kind of an experiment explaining what's going on behind the scenes.
Ex(1st Article): https://purpleidea.com/blog/2016/01/18/next-generation-configuration-mgmt/

After reading a bit more, I see words like puppet, then I realize, it's just another devops tool.

I come from years of Ansible background experience, I must say the language is beautiful and more intuitive and powerful compared to Ansible's yaml.
It just needs decent tutorials, As end users, Most of us don't want to know or see articles about how amazing it is internally(most of the docs is just this), we want to know how amazing it is for us to use.

A really simple tutorial like: 
Given three servers A, B, C with IPs 1.1.1.1, 1.1.1.2, 1.1.1.3
1. How do I install/configure nginx+php (most of the web uses this any) in all three and deploy a 'hello world' index.php page.
2. where do I specify the IPs? (pull vs push) 
3. Is there a master server? How do I set it up?  or how do I setup an agent?
4. Do I need to copy the binary in all three to begin with? 

5. How do I standard stuff like:
- Install a package (nginx+php-fpm)
- copy/download files from somewhere else (the code, ex: index.php)
- fetch latest code from git
- unzip/untar files
- apply some templates/configs (file like httpd.conf, php.ini etc)
- start and stop services, execute commands 

6. How do I view the results/logs?

This has a lot of potential but looks like it is just not being sold to the right people.
A basic tutorial like the one mentioned above will take it really far, It doesn't have to be PHP-Nginx, it could be java or node, we just need some real world tutorials. I am keen to help as well. 

For beginners, we can start by answering points, 2,3 & 4

**Comment by purpleidea** [comment]
@avierr I agree! Would you like to contribute such a tutorial? I'm not being paid for this work, and so I spend my focus on the parts I want for myself, which currently is fixing bugs so it's more production ready.

Patches welcome and donations too! https://www.patreon.com/purpleidea

Thanks!

**Comment by avierr** [comment]
@purpleidea 
Yes I would love to contribute.

as I said above, please the following or point me to the right place:
```
I am keen to help as well.

For beginners, we can start by answering points, 2,3 & 4
```

**Comment by purpleidea** [comment]
@avierr I can't write a tutorial for you at the moment, but if you'd like to watch a recent video and do more reading, then I think you'll figure it out, and then you can build a tutorial. Some recent talks I gave are here: https://purpleidea.com/talks/

If you have golang programming skills, please join us in #mgmtconfig on Freenode IRC and I can help get you going.

Thanks!
