### ISSUE TITLE
An interesting change for file state and content

### ISSUE THREAD

**Issue by purpleidea** [purpleidea/mgmt#540]
Consider:

```
file "/tmp/foo" {
        content => "hello\n",
}
```

Suppose there's an existing file at `/tmp/foo`, then this is a no-brainer, we edit the file so that it has the expected contents of `hello`.

But suppose no file exists? Should we create one or not?

Puppet does, and at the moment, we do too, because we _imply_ from the content specification that we'd want one. But it turns out that it actually makes our code more complex to do so, and it makes the _reversible resource_ code slightly illogical because of the implied state.

When I think about it, perhaps it's a mistake in general to ever imply the state. Same logic for specifying `mode` or any other property if the file is missing.

What are you thoughts?
What does chef, ansible, or any other tool do?
Maybe puppet got this one wrong? Let's get it right!

**Comment by ffrank** [comment]
For Ansible the question is muddled by the fact that the `file` module won't even allow you to manage content. You have to use `copy`. And it would feel illogical for `copy` to ever *not* create a file at destination because, well, `cp` right?

So this creates a file:

```
ansible -m copy -a'dest=/tmp/newfile2 content="hullo\n"' localhost
```

Notably though, the following errors out (at least w/ good old Ansible 2.2)

```
ansible -m file -a'dest=/tmp/newfile3 mode=0644' localhost
```

**Comment by purpleidea** [comment]
According to felix:

```
puppet apply -e 'file {"/tmp/newfile": content => "hullo\n"}'
ansible -m copy -a'dest=/tmp/newfile2 content="hullo\n"' localhost
```
> both seem to agree that yes, you wanted the file to be created implicitly

What about chef? @nathenharvey ?

**Comment by purpleidea** [comment]
@markburgess What do you think? What does old cfengine or cfengine3 do? What do you think is correct?

**Comment by ffrank** [comment]
FWIW I'm having a hard time even gauging the least surprise in this scenario.

**Comment by purpleidea** [comment]
> FWIW I'm having a hard time even gauging the least surprise in this scenario.

The least surprise has to do with what is _more_ *correct*, since our goal (at least for mgmt) is safety. So this means you'd have to explicitly specify that you want a file created.

As a side-effect, if you didn't specify `state` and that was because there was always a file created beforehand (eg from some shell script or provisioning thing) then this would error in response to that previous script not behaving the same, so this is potentially a win.

**Comment by ncharles** [comment]
In CFEngine 3, by default the file is *not* created. So you have to specify if you want it created (attribute create => "true")

In Rudder, if we specify content for a file, then we create it by default if it's not present 

I think the sane default is to create the file if we expect some content in it (with an option to not create it). On the other hand, if we want to *remove* content from a file, creating the file seems pointless.

Finally, the topic of reporting in this case is funny-ish. If you make a file promise in CFEngine, you specify several attribute:

- existence
- permissions
- content
- (and some less common things

Agent may change any of these attribute, causing a global repair status of the promise. Then, it's really hard to know what was effectively repaired (was it the content? the permission?) unless by reading attentively the output of the agent.
This is something that can be done in a better way in mgmt I think

**Comment by purpleidea** [comment]
@ncharles So to confirm, if you specify file content but NOT `create => true` then it errors? Cool.

**Comment by ncharles** [comment]
Yes, that's correct for CFEngine.

**Comment by nathenharvey** [comment]
Each chef resource has an `action`.  The `file` resource has 5 different possible actions:

* `:create`
* `:create_if_missing`
* `:delete`
* `:nothing`
* `:touch`

If no action is specified, the default is used.  The default action varies by resource.  The `:create` action is the default action for the `file` resource.

Here's what happens with each action:

* action - not specified, uses `:create` as that is the default:  `foo-0` created
* action - `:create`:  `foo-1` created
* action - `create_if_missing`:  `foo-2` created
* action - `:delete`: no file to delete, no change, no error
* action - `:nothing`: no change
* action - `:touch`:  `foo-5` created with content

The chef recipe is:

```
file '/tmp/foo-0' do
  content "hello\n"
end

file '/tmp/foo-1' do
  content "hello\n"
  action :create
end

file '/tmp/foo-2' do
  content "hello\n"
  action :create_if_missing
end

file '/tmp/foo-3' do
  content "hello\n"
  action :delete
end

file '/tmp/foo-4' do
  content "hello\n"
  action :nothing
end

file '/tmp/foo-5' do
  content "hello\n"
  action :touch
end
```

https://docs.chef.io/resource_file.html

**Comment by purpleidea** [comment]
@nathenharvey Very helpful, thank you!!

**Comment by purpleidea** [comment]
Tentative patch in: https://github.com/purpleidea/mgmt/commit/1dfffb19e3259a679602d97e5b53db543c85a907

(Tests still running, perhaps I missed something somewhere, but have a look.)

I also did a bit of cleanup while writing this, so it's slightly more busy than it should be. But I'm really liking this idea.

**Comment by purpleidea** [comment]
Updated: b01cda159c3c3f48e478ce6f5c2b1be7c23747ea

**Comment by purpleidea** [comment]
This all passed now, so I'm going to let this sit for at least 24ish, and if I don't hear any strong complaints, I think I'll be tempted to merge it.

**Comment by purpleidea** [comment]
Okay, merged!
