### ISSUE TITLE
Cannot build latest master

### ISSUE THREAD

**Issue by ffrank** [purpleidea/mgmt#55]
Using `go1.5.4`, this is what I'm getting:

```
Building: mgmt.static, version: 0.0.3-61-ga1ed034...
go generate
stringer: checking package: etcd.go:119:15: OpOption not declared by package etcd
event.go:20: running "stringer": exit status 1
Makefile:78: recipe for target 'mgmt.static' failed
make: *** [mgmt.static] Error 1
```

**Comment by purpleidea** [comment]
@ffrank Does https://github.com/purpleidea/mgmt/pull/56 fix your issue? Git master is broken on 1.6.x but not on 1.5.x for me. Vendoring sucks :(

**Comment by purpleidea** [comment]
@ffrank Build is officially not broken anymore on travis. If it's broken for you, probably something is wrong/old in your $GOPATH.

Having said all this, figuring out how this godep nonsense works is turning out to be a pain. This is surely related to why golang 1.6 builds aren't working. If someone wants to work on that, please LMK.

**Comment by purpleidea** [comment]
Note: I'm going to try and port the code to the "embed" code, so maybe after that's working it will get easier dep wise. https://godoc.org/github.com/coreos/etcd/embed

**Comment by ffrank** [comment]
Well I did also try a fresh GOPATH, but ran into the issues addressed in #56. Tiring.

**Comment by purpleidea** [comment]
@ffrank I have moved to the new embed etcd code. If you still have this issue please let me know, or create another or ping me in IRC. Thanks!

**Comment by ffrank** [comment]
Hmm, ran into another issue after today's `pull` that required me to `rm *_stringer.go`.

This used to be covered by `make clean`, but not anymore since 2a0a69c. What's the reasoning here?

**Comment by purpleidea** [comment]
On Wed, Jul 27, 2016 at 6:21 PM, Felix Frank <notifications@github.com>
wrote:

> Hmm, ran into another issue after today's pull that required me to rm
> *_stringer.go.
>
> This used to be covered by make clean, but not anymore since 2a0a69c
> <https://github.com/purpleidea/mgmt/commit/2a0a69c917c4108632cb6b186d5042c22e6b39c4>.
> What's the reasoning here?
>

Good question! The go generate command is broken in terms of some vendoring
stuff, or at least behaved strangely, so i just stopped including the
stringing. It works without it. If you want the strings, just run it.
