### ISSUE TITLE
Gratuitous stderr redirection in Makefile

### ISSUE THREAD

**Issue by ffrank** [purpleidea/mgmt#568]
## Versions:

* mgmt version (eg: `mgmt --version`): git master

* operating system/distribution (eg: `uname -a`): `Linux dev-app01-ffrank 4.4.0-140-generic #166-Ubuntu SMP Wed Nov 14 20:09:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

* golang version (eg: `go version`): 1.11.5

## Description:

Issues from unclean build environments can currently be hidden by Makefile rules.

```
t$ go run `find lang/funcs/funcgen/ -maxdepth 1 -type f -name '*.go' -not -name '*_test.go'` -templates=lang/funcs/funcgen/templates/generated_funcs.go.tpl
lang/funcs/funcgen/pkg.go:31:2: cannot find package "github.com/iancoleman/strcase" in any of:
        /home/demo/go/src/github.com/purpleidea/mgmt/vendor/github.com/iancoleman/strcase (vendor tree)
        /usr/lib/go-1.11/src/github.com/iancoleman/strcase (from $GOROOT)
        /home/demo/go/src/github.com/iancoleman/strcase (from $GOPATH)
```

But as the Makefile rule includes `2> /dev/null`, the failure is very cryptic:

```
$ make lang/funcs/core/generated_funcs.go
Generating: funcs...
Makefile:510: recipe for target 'lang/funcs/core/generated_funcs.go' failed
make: *** [lang/funcs/core/generated_funcs.go] Error 1
```

Discarding stderr is never a good idea in the build process and should be avoided, at least in rules like this one.

**Comment by purpleidea** [comment]
The problem is that the normal behaviour is logged to stderr as well which makes a mess in my terminals. if you'd like to play with https://golang.org/pkg/log/#SetOutput or similar and propagate errors properly and only print good things to stdout and bad things to stderr then happy to do this.
