### ISSUE TITLE
exec watchcmd delays shutdown

### ISSUE THREAD

**Issue by ffrank** [purpleidea/mgmt#585]
## Versions:

* mgmt version (eg: `mgmt --version`): 
```
mgmt version 0.0.21-65-g1f6640c
```

* operating system/distribution (eg: `uname -a`): 
```
Linux dev-app01-ffrank 4.4.0-140-generic #166-Ubuntu SMP Wed Nov 14 20:09:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

* golang version (eg: `go version`):
```
go version go1.13.4 linux/amd64
```

## Description:

When running the following code
```
exec "very significant program" {
  cmd => "echo pling",
  shell => "/bin/bash",
  watchcmd => "while : ; do echo now ; sleep 30 ; done",
  watchshell => "/bin/bash",
}
```
and stopping `mgmt` using `Ctrl-C`, the software hangs up to 30 seconds (after the message `main: destroy...` until the shutdown commences.

Hitting `Ctrl+C` repeatedly kills more goroutines (messily), but the tool does not stop until the watchcmd prints its last line of output.

**Comment by purpleidea** [comment]
This is by design. A kill is sent to the Watch command, but that's up to it to decide whether to die or not.

There is a resource extension called InterruptableRes:
