### ISSUE TITLE
Parser panic on []struct types with duplicate member names

### ISSUE THREAD

**Issue by HerrSpace** [purpleidea/mgmt#591]
## Versions:

* mgmt version (eg: `mgmt --version`):
git commit be39fbeff6812e35454f0381f9ad551ac4f776c2

* operating system/distribution (eg: `uname -a`):
mac os 10.15.2

* golang version (eg: `go version`):
go version go1.13.8 darwin/amd64

## Description:
Parsing `$d []struct{x int;x int}` via the MCL parser causes the following panic:

```
panic: malformed struct length

goroutine 1 [running]:
github.com/purpleidea/mgmt/lang/types.(*Type).String(0xc0001f7450, 0x14, 0xc0001f7450)
	/Users/space/repos/go/src/github.com/purpleidea/mgmt/lang/types/type.go:520 +0xa1b
github.com/purpleidea/mgmt/lang.(*yyParserImpl).Parse(0xc000107000, 0x4c802c0, 0xc0001f72c0, 0x0)
	parser.y:1168 +0xdd3d
github.com/purpleidea/mgmt/lang.yyParse(...)
	yaccpar:153
github.com/purpleidea/mgmt/lang.LexParse(0x4c74ea0, 0xc0001ece10, 0xc000010018, 0x402eefa, 0xc0001bdef8, 0xc000010018)
	/Users/space/repos/go/src/github.com/purpleidea/mgmt/lang/lexparse.go:95 +0xbe
github.com/purpleidea/mgmt/fuzz.Fuzz(0xc000114000, 0x19, 0x219, 0x19)
	/Users/space/repos/go/src/github.com/purpleidea/mgmt/fuzz/fuzz.go:18 +0x7e
main.main()
	/Users/space/repos/go/src/github.com/purpleidea/mgmt/main.go:21 +0x164
exit status 2
```

Looking at `parser.y` it seems we crash in the string conversion here:
```
|	OPEN_BRACK CLOSE_BRACK type
	// list: []int or [][]str (with recursion)
	{
		posLast(yylex, yyDollar) // our pos
		$$.typ = types.NewType("[]" + $3.typ.String())
	}
```

Looking at `types.String` we see we crash in the second check here:
```go
	case KindStruct: // {a bool; b int}
		if obj.Map == nil {
			panic("malformed struct type")
		}
		if len(obj.Map) != len(obj.Ord) {
			panic("malformed struct length")
		}
```

And indeed, when trying to parse the type manually via `types.NewType` we get some object like:
```
&types.Type{
  Kind: 5,
  Val:  &types.Type{
    Kind: 7,
    Val:  (*types.Type)(nil),
    Key:  (*types.Type)(nil),
    Map:  map[string]*types.Type{
      "x": &types.Type{
        Kind: 3,
        Val:  (*types.Type)(nil),
        Key:  (*types.Type)(nil),
        Map:  map[string]*types.Type{},
        Ord:  []string(nil),
        Out:  (*types.Type)(nil),
        Var:  (*types.Type)(nil),
      },
    },
    Ord: []string{
      "x",
      "x",
    },
    Out: (*types.Type)(nil),
    Var: (*types.Type)(nil),
  },
  Key: (*types.Type)(nil),
  Map: map[string]*types.Type{},
  Ord: []string(nil),
  Out: (*types.Type)(nil),
  Var: (*types.Type)(nil),
```

The dict only contains "x" once, hence the length mismatch.

I tried to come up with a patch, but the best I could come up with is:
```go
diff --git a/lang/types/type.go b/lang/types/type.go
index e51bafb..13cdf02 100644
--- a/lang/types/type.go
+++ b/lang/types/type.go
@@ -291,8 +291,13 @@ func NewType(s string) *Type {
                                return nil
                        }
                        key := s[:sep] // FIXME: check there are no special chars in key
-                       keys = append(keys, key)

+                       // abort on duplicate struct member names
+                       if _, contained := tmap[key]; contained {
+                               return nil
+                       }
+
+                       keys = append(keys, key)
                        s = s[sep+1:] // what's next

                        var found int
```

which doesn't actually work.  When lexing/parsing our MCL again this gives us something like:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4625c67]

goroutine 1 [running]:
github.com/purpleidea/mgmt/lang/types.(*Type).String(0x0, 0x14, 0x0)
	/Users/space/repos/go/src/github.com/purpleidea/mgmt/lang/types/type.go:491 +0x37
github.com/purpleidea/mgmt/lang.(*yyParserImpl).Parse(0xc0000f1000, 0x4c802c0, 0xc0001c92c0, 0x0)
	parser.y:1168 +0xdd3d
github.com/purpleidea/mgmt/lang.yyParse(...)
	yaccpar:153
github.com/purpleidea/mgmt/lang.LexParse(0x4c74ea0, 0xc0001bae10, 0xc000010cd8, 0x402eeba, 0xc00018def8, 0xc000010cd8)
	/Users/space/repos/go/src/github.com/purpleidea/mgmt/lang/lexparse.go:95 +0xbe
github.com/purpleidea/mgmt/fuzz.Fuzz(0xc0002ec000, 0x19, 0x219, 0x19)
	/Users/space/repos/go/src/github.com/purpleidea/mgmt/fuzz/fuzz.go:18 +0x7e
main.main()
	/Users/space/repos/go/src/github.com/purpleidea/mgmt/main.go:21 +0x164
exit status 2
```

So at this point I think either `NewType` should return an `err` too or the lexer/parser should already catch duplicate member names. What do you think?

Interacting with this auto generated code is a bit difficult, is there some good debugger integration for this stuff?

**Comment by purpleidea** [comment]
Yikes! Nice find, and lovely story about getting here with the fuzzer! Would you prefer that I whip up a patch, or make a recommendation about how I would fix it and let you get the commit points?

> So at this point I think either NewType should return an err too or the lexer/parser should already catch duplicate member names. What do you think?

Great question. I think NewType should keep the simple API because it makes its use significantly easier, and it's meant as an internal-only API. The bug is me not catching the invalid input from the Lexer/Parser (and perhaps anywhere else... ?)

> Interacting with this auto generated code is a bit difficult, is there some good debugger integration for this stuff?

The code is in parser.y, I'd look there...

Also, if you do want to patch this, please include a test in lang/types/ as well! Thanks!

**Comment by purpleidea** [comment]
I didn't hear from you, so I wrote a patch. Here it is:

https://github.com/purpleidea/mgmt/commit/70eecd52895b2bbfeddff6daded09f9e849d6374

(Waiting for tests before I merge...)

Thanks again!

**Comment by purpleidea** [comment]
merged! Thanks again.
