### ISSUE TITLE
Feature: CIDR to IP converter

### ISSUE THREAD

**Issue by dbakong** [purpleidea/mgmt#596]
#### Intro:
Mgmt has a language - mcl -  and it currently doesn't have a function to accept an ip address in CIDR form and return the IP by itself. 
#### Design:
The functionality would rely on Golang's default net package - specifically [net.ParseCIDR](https://golang.org/pkg/net/#ParseCIDR) to allow mcl to convert the IP address from CIDR form. The function would take an IP in the form "192.168.23.5/24" and return "192.168.23.5".
The patch would also use the [simple function api](https://github.com/purpleidea/mgmt/tree/master/lang/funcs/simple). 

The tests for this patch would cover:
- The suggested return type
- The actual converted IPs
- Valid input
- Expected errors

The signature of the function would be similar to the below:
ParseCIDR(s string) (IP, error) - the CIDR address would be accepted as a string and the function would return the IP or an error. The function would accept both IPv4 and IPv6 addresses. Invalid CIDR addresses would need to be handled. Some errors would include:
- Incorrect address length - e.g. 10.0.1/24
- Invalid digits - e.g. 10.0.0.0/33
- Other forms of incorrect input - e.g. letters in IPV4 address, etc.

**Comment by purpleidea** [comment]
> The function would return all IP addresses within a CIDR range(1, 2).

This assumption is incorrect for my intention, rather it's intended to take an IP in the form: "192.168.23.5/24" and return "192.168.23.5" -- it's true we might have different functions to determine ranges, etc, but let's start simple.

Update your above proposal, and include a short discussion about the `signature` of the function, errors (if any) and anything else you might want to mention. There's one more obvious thing you should discuss which wasn't mentioned.

**Comment by dbakong** [comment]
Additions to the IP parsing patch in the net package could include new functions for the following:
- Return IP network/Mask from an IP address
- IP address comparison (checking if 2 IPs are equal)
- URL parsing for hostname, port, path?query or opaque?query string, etc

**Comment by dbakong** [comment]
This is complete with @ #598
