### ISSUE TITLE
help does not show a list of commands

### ISSUE THREAD

**Issue by joejulian** [purpleidea/mgmt#60]
According to the help text:

```
$ mgmt --help
NAME:
   mgmt - next generation config management

USAGE:
   mgmt [global options] command [command options] [arguments...]
   
VERSION:
   0.0.3
   
COMMANDS:
     run, r   run
     help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --help, -h     show help
   --version, -v  print the version
```

So my expectation is that `mgmt help` will show me a list of commands. Instead it shows the exact same help text.

mgmt version 0.0.3

**Comment by joejulian** [comment]
Oh, wait.. is "run" the only other command? Maybe it is working as intended after all.

**Comment by purpleidea** [comment]
@joejulian Yeah, run is the only command for now. We'll eventually have other utility commands in the future I expect. You can do `mgmt run --help` to get what you're looking for.
