### ISSUE TITLE
EL packages - any plans to resurrect and maintain the EL7 releases?

### ISSUE THREAD

**Issue by bby-bishopclark** [purpleidea/mgmt#609]
## Description:

I notice in the FAQ that the EL7 packages are listed as 'dead' in COPR and are 5 years old.  Is there a plan to resurrect this deployment spur ?

For many of us, a packaged install is a deal-maker (or deal-breaker!) and some of us will silently just skip over a project with no enterprise release.

Thanks!

**Comment by purpleidea** [comment]
@bby-bishopclark Sorry for the delayed reply. This project isn't really funded, it's done in my spare time. If you'd like to fund this feature, please let me know! Free software isn't gratis. Sorry it's not the answer you might want, but I want to be honest about my available resources. Thanks!

**Comment by bby-bishopclark** [comment]
Totally understandable; we just disagree about chickens and eggs.  :-D

Ah, so it's just 'make srpm', then.  Did the build break without a budget to fix it, and that's why EL7 wasn't being produced?  Looks like it could Just Work but - same deal - spare time.   Let you know!

**Comment by purpleidea** [comment]
@bby-bishopclark Yeah, day-to-day, I'm not testing or building continuous builds. I do publish binaries in https://github.com/purpleidea/mgmt/releases but it's not using COPR atm. There is some Makefile stuff about copr, but I haven't looked recently. I'm more focused on fixing the bug or two that's bugging me, and adding an important feature that I want. After then, we might circle around with more packages. TBD. If you'd like to contribute time or money, please let me know!
