### ISSUE TITLE
Issue building mgmt

### ISSUE THREAD

**Issue by eviscares** [purpleidea/mgmt#613]
## Versions:

* mgmt version (eg: `mgmt --version`):
-
* operating system/distribution (eg: `uname -a`):
Ubuntu 18.04
* golang version (eg: `go version`):
go version go1.15.2 linux/amd64
## Description:
Hi,

I'm trying to build mgmt and I'm running into some issues here when I try to make deps.

> running 'go get -v -d ./...' from /root/go/src/github.com/purpleidea/mgmt
package github.com/purpleidea/mgmt
	imports github.com/purpleidea/mgmt/lib
	imports github.com/purpleidea/mgmt/bindata: no Go files in /root/go/src/github.com/purpleidea/mgmt/bindata

Please advise whether I am just too stupid or if there is something wrong with the dependencies.

Cheers

**Comment by purpleidea** [comment]
@eviscares You're not stupid! Please follow the quick start guide: https://github.com/purpleidea/mgmt/blob/master/docs/quick-start-guide.md

You probably want `make deps`.

And if you're curious about the specific issue, it has to do with the fact that the `bindata` stuff is generated code. This was necessary before the `go:embed` stuff existed. And we'll keep using it for a while and the embed stuff is in a version we want to support.

Of course you might also prefer just using a release: https://github.com/purpleidea/mgmt/releases

HTH

(Ping if this didn't solve your issue, but I will close for now.)

**Comment by eviscares** [comment]
Thanks for the advice, but it doesn't seem to work, as I have the aforementioned error when trying to `make deps`. I will switch to using a release for now, but I would like to get this to build in the future to maybe hack away at it.

**Comment by purpleidea** [comment]
@eviscares At this point you should already have all the deps installed. Try:

`make`

Does it build?
Next check that `go-bindata` is in your $PATH somewhere...

LMK what `which go-bindata` replies.

**Comment by purpleidea** [comment]
I'm closing for now. If you provide more information we can reopen.
