### ISSUE TITLE
mips build?

### ISSUE THREAD

**Issue by bish0polis** [purpleidea/mgmt#614]
Hey everyone,

Anyone building for mips yet?  

Is it even possible?

**Comment by purpleidea** [comment]
@bish0polis No idea, but it would depend on golang. If you'd like to work on this let me know and I'll re-open the issue.

**Comment by purpleidea** [comment]
(To clarify, I don't have hardware for this, nor do I know how well golang works at all on this arch. Let us know.)

**Comment by bish0polis** [comment]
I'm not a good candidate to work on this one, sadly.  I have no Go experience, and Rust is gentler for us C kids so it may slide in before Go.  I have one class of MIPS-LE devices in mind (the ER-X) and proper management would have been cool if I were to scale these out as part of a private project.

**Comment by purpleidea** [comment]
@bish0polis Golang does have `linux/mipsle` but there are some limitations. I haven't tried it. If your company has a ton of these devices and want to send me one, I can play around with it, but it will be all "best effort" and I can't guarantee any success or how much time I can devote to it.

HTH

**Comment by bish0polis** [comment]
It's a family project, unfortunately.  Thanks anyway!
