### ISSUE TITLE
we should add the SO_REUSEADDR options to etcd

### ISSUE THREAD

**Issue by purpleidea** [purpleidea/mgmt#651]
This is fixed now I think: https://github.com/etcd-io/etcd/issues/6042
We should add the options in and test.

**Comment by purpleidea** [comment]
```
	cfg.SocketOpts = transport.SocketOpts{
		//ReusePort: false, // SO_REUSEPORT
		ReuseAddress: true, // SO_REUSEADDR
	}
```

Patch is this ^^ into etcd/server.go but we need to wait for the 3.5 release first.

**Comment by purpleidea** [comment]
I have this in a feature branch btw, but waiting for the etcd release.

**Comment by souradeepmajumdar05** [comment]
can you add the branch details here

**Comment by purpleidea** [comment]
This patch was already merged, and was just left open to test. If you want to write some tests of this, please do! Closing the issue for now.
