### ISSUE TITLE
add go.mod and go.sum as deps in the Makefile

### ISSUE THREAD

**Issue by purpleidea** [purpleidea/mgmt#693]

**Comment by nikzayn** [comment]
@purpleidea It would be good if you brief me more about this issue, or I just add go.mod and go.sum in the makefile. Can you provide helpful links to which I can refer?

**Comment by purpleidea** [comment]
Yeah this was fairly badly documented, sorry. It seems this was already done in b6502693e46f33faee158a928d3240e071b4203f so there's nothing left to do here, so I will close this. If you're in the mood for some Makefile hacking or looking for another patch to work on, please let me know!
