### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by gedw99** [purpleidea/mgmt#705]
Are there any docs ?? 

the markdown is very general .

**Comment by purpleidea** [comment]
Look in docs/ and also there is godoc generated docs. There are also blog posts and talks recorded. All listed. You can also help improve the docs by discussing with us and then sending patches.

**Comment by purpleidea** [comment]
One last note, I've also tried to make this more clear in this commit: https://github.com/purpleidea/mgmt/commit/3f5957d30ef89ab92ae55ba3d326abfde993cfa2

**Comment by gedw99** [comment]
Sone basic examples would really help

**Comment by purpleidea** [comment]
quick start docs show it.

**Comment by gedw99** [comment]
Ok will try again to get it working on my side .. thanks
