### ISSUE TITLE
FR (packagekit): allow refreshing the cache

### ISSUE THREAD

**Issue by pauhull** [purpleidea/mgmt#712]
Hi,

I'm currently using this repo's PackageKit bindings in my Go project, since there is no other library available. It would be nice to have a mapping for the [RefreshCache](https://www.freedesktop.org/software/PackageKit/gtk-doc/Transaction.html#Transaction.RefreshCache) method, because GetUpdates() will only return cached and possibly out of date packages otherwise.

Since there have been no changes to packagekit.go for a few years and RefreshCache() is probably not needed for your project, I can imagine that this FR would not have very high priority. It would still be possible to spawn ``pkcon refresh`` subprocess, although a mapping in the library would be better. Please let me know if you are interested in implementing this.

Best regards

**Comment by purpleidea** [comment]
Patches are certainly welcome! If you cannot write the patch but want such a feature anyways, then you would have to pay money for it, but that could probably be arranged. Cheers

**Comment by purpleidea** [comment]
Btw, your https://github.com/pauhull/bananascript/ library looks really interesting! Maybe helping out with our compiler would be really fun for you! We'd certainly appreciate it.
