### ISSUE TITLE
Build fails with invalid value for flag -ldflags

### ISSUE THREAD

**Issue by saraedum** [purpleidea/mgmt#752]
## Versions:

* mgmt version (eg: `mgmt --version`): master branch ([964b1dc](https://github.com/purpleidea/mgmt/commit/964b1dc58aa0197d8579b89e02f36ec11a7771c2))

* operating system/distribution (eg: `uname -a`): technically `Linux wigwum 6.8.2-arch2-1 #1 SMP PREEMPT_DYNAMIC Thu, 28 Mar 2024 17:06:35 +0000 x86_64 GNU/Linux` but this is about a docker build

* golang version (eg: `go version`): whatever the docker image uses

## Description:

I tried to follow the quickstart instructions. But `buildah build -f Dockerfile-fedora.build -t mgmt_build` fails with

```
STEP 14/15: RUN make build
go: updates to go.mod needed; to update it:
	go mod tidy
Generating: lexer...
Generating: parser...
Generating: interpolation...
Generating: type kind strings...
Generating: funcs...
go: downloading github.com/iancoleman/strcase v0.3.0
Building: mgmt, os/arch: linux-amd64, version: 0.0.26-1-g964b1dc5...
time env GOOS=linux GOARCH=amd64 go build -trimpath -ldflags=="-X main.program=mgmt -X main.version=0.0.26-1-g964b1dc5 -s -w " -o build/mgmt-linux-amd64
invalid value "=-X main.program=mgmt -X main.version=0.0.26-1-g964b1dc5 -s -w " for flag -ldflags: missing <pattern> in <pattern>=<value>
usage: go build [-o output] [build flags] [packages]
```

**Comment by purpleidea** [comment]
The docker build is really unmaintained as I don't think anyone is using it, so it likely rotted. I'd recommend just doing `make` in a vm. Maybe something about `buildah` is different? Do you see the same issue with regular docker?

**Comment by saraedum** [comment]
> Maybe something about `buildah` is different? Do you see the same issue with regular docker?

`docker build -t mgmt-debian -f docker/Dockerfile .` seem to work.

**Comment by purpleidea** [comment]
TBQH, I never use docker, so I usually just merge whatever the last person says was necessary for anything docker related =D
