### ISSUE TITLE
Looking for docs and modules!

### ISSUE THREAD

**Issue by IngwiePhoenix** [purpleidea/mgmt#754]
## Versions:

* mgmt version: N/A
```
Building: mgmt, os/arch: linux-riscv64, version: 0.0.26-7-g909dbb53...
time env GOOS=linux GOARCH=riscv64 go build -trimpath -ldflags=="-X main.program=mgmt -X main.version=0.0.26-7-g909dbb53 -s -w " -o build/mgmt-linux-riscv64
invalid value "=-X main.program=mgmt -X main.version=0.0.26-7-g909dbb53 -s -w " for flag -ldflags: missing <pattern> in <pattern>=<value>
usage: go build [-o output] [build flags] [packages]
Run 'go help build' for details.

real    0m0.017s
user    0m0.004s
sys     0m0.014s
make: *** [Makefile:229: build/mgmt-linux-riscv64] Error 2
```

* operating system/distribution (eg: `uname -a`): Debian "sid/trixie"

* golang version (eg: `go version`): 1.22.1 linux/riscv64

## Description:

Hello there!

So, to cut a long story short, I came here after [I had asked on the OpenTofu subreddit](https://www.reddit.com/r/opentofu/comments/1c2pbu7/i_am_trying_to_get_started/) for some advice and help. Well, whilst OpenTofu - and thus also Terraform - are not what I had been after, due to a misunderstanding on my end, I started to look into Ansible and friends. But since I am just personally not a Python-friend, I decided to look further - and thus, ended up here.

As you can see above, I have a RISC-V box (VisionFive2) that I would like to use as a mgmt seed/deploy server; there is not much else I can run on it as it is, so I want to use this as a starting point.

The build issues aside (I am quite sure it's the architecture throwing the build script off), I have crawled this repo up and down, trying to find a table or list of all the various built-in classes and modules to ensure the state of files, values and friends. Where is it? I am not the most proficient with Go, but this is quite a big repo so finding something might be difficult...

Would appreciate any pointer so that I can see what is there and what else might need implementing. For instance, right now, there does not seem to be support for Alpine Linux (apk) or OpenWrt (opkg) - so I might want/have to add implementations for those...but right now, I don't really know where to start, let alone what is there already.

Ideally, I want to reach a state where I have a few shared configurations and a few that are host-specific. The deeds for that are in the linked Reddit post, if interested.

Thanks and kind regards,
Ingwie

**Comment by purpleidea** [comment]
> , I have crawled this repo up and down, trying to find a table or list of all the various built-in classes and modules to ensure the state of files, values and friends. Where is it?

Sorry for that! We should definitely improve the docs somehow, and at some point we'll take the code and built-in docs and auto-generate some official doc site. If you want to work on that please let me know.

To answer your question we have resources and functions.

Probably easiest to see resources here: https://godocs.io/github.com/purpleidea/mgmt/engine/resources

And functions here: https://github.com/purpleidea/mgmt/tree/master/lang/core

The functions are harder to browse, but we have a way to improve that if someone wants to write the patch.


As for riscv: I'd love to get it running there but I have zero hardware to test. For this scenario, there are a few options:

1) You could sponsor some hardware.

2) You could send any patches and if they look obvious, I can merge them.

3) If it's a complex patch that I won't be able to confirm is safe and I don't have any hardware to test on, then you're out of luck for getting your patch upstream.

HTH

**Comment by IngwiePhoenix** [comment]
Thanks for the resources!

As for RISCV, I glanced the Makefile and I spotted the obvious; you currently don't have any `PROGNAME` or alike to generate the RISCV suffix. So, the build command above, was just missing that variable. I'll get to work on that. :)

As for hardware... Well, actually, you can use QEMU. The folks at [OpenADK](https://openadk.org) have a build system that can build a nice QEMU image and even use that for testing. I had reported issues with ucLibc on RISCV before while trying to build a bootstrap container to build things in to get Alpine 3.19 ported. Chances are this could be a stopgap solution.

Also, Go's `GOARCH` has a riscv64 value, you can crosscompile. :)

Anyway, you'll hear from me soon when I have that fixed; this shouldn't take too much time to at least get a build.

Kind regards,
Ingwie

**Comment by IngwiePhoenix** [comment]
So as it turns out, very early on, while evaluating `PROGNAME`, Go threw an error which you can see in the very first two lines of my log post. Completely overlooked that, oops.

With that done - running the suggested `go mod tidy` - , it is now building! I also went and copied each instance of `arm64` and added it as `riscv64`.

I haven't tried any of the other Make targets, but here you go!
```
root@riscboi /n/o/mgmt (master)# make
Building: mgmt, os/arch: linux-riscv64, version: 0.0.26-7-g909dbb53-dirty...
time env GOOS=linux GOARCH=riscv64 go build -trimpath -ldflags=github.com/purpleidea/mgmt="-X main.program=mgmt -X main.version=0.0.26-7-g909dbb53-dirty -s -w " -o build/mgmt-linux-riscv64

real    7m28.822s
user    20m18.141s
sys     1m33.998s
cp -a build/mgmt-linux-riscv64 mgmt
root@riscboi /n/o/mgmt (master)# ./mgmt --version
0.0.26-7-g909dbb53-dirty
```

```diff
diff --git a/Makefile b/Makefile
index 346e20b0..0bd986f7 100644
--- a/Makefile
+++ b/Makefile
@@ -67,7 +67,7 @@ REMOTE_PATH = '/srv/pub/alt/$(USERNAME)/$(PROGRAM)'
 ifneq ($(GOTAGS),)
        BUILD_FLAGS = -tags '$(GOTAGS)'
 endif
-GOOSARCHES ?= linux/amd64 linux/ppc64 linux/ppc64le linux/arm64 darwin/amd64
+GOOSARCHES ?= linux/amd64 linux/ppc64 linux/ppc64le linux/arm64 linux/riscv64 darwin/amd64

 GOHOSTOS = $(shell go env GOHOSTOS)
 GOHOSTARCH = $(shell go env GOHOSTARCH)
@@ -76,6 +76,7 @@ GOHOSTARCH = $(shell go env GOHOSTARCH)
 # "FEDORA-LATEST", etc...) and the arch ("AMD64"). The distro can have a dash.
 TOKEN_BINARY_AMD64 = $(shell grep -v '#' releases/binary-amd64.release)
 TOKEN_BINARY_ARM64 = $(shell grep -v '#' releases/binary-arm64.release)
+TOKEN_BINARY_RISCV64 = $(shell grep -v '#' releases/binary-riscv64.release)
 TOKEN_FEDORA-LATEST = $(shell grep -v '#' releases/fedora-latest.release)
 TOKEN_FEDORA-OLDER = $(shell grep -v '#' releases/fedora-older.release)
 TOKEN_STREAM-LATEST = $(shell grep -v '#' releases/stream-latest.release)
@@ -85,6 +86,7 @@ TOKEN_ARCHLINUX = $(shell grep -v '#' releases/archlinux.release)

 FILE_BINARY_AMD64 = mgmt-linux-amd64-$(VERSION)
 FILE_BINARY_ARM64 = mgmt-linux-arm64-$(VERSION)
+FILE_BINARY_RISCV64 = mgmt-linux-riscv64-$(VERSION)
 # TODO: add ARCH onto these at the end, eg _AMD64
 FILE_FEDORA-LATEST = mgmt-$(TOKEN_FEDORA-LATEST)-$(VERSION)-1.x86_64.rpm
 FILE_FEDORA-OLDER = mgmt-$(TOKEN_FEDORA-OLDER)-$(VERSION)-1.x86_64.rpm
@@ -95,6 +97,7 @@ FILE_ARCHLINUX = mgmt-$(TOKEN_ARCHLINUX)-$(VERSION)-1-x86_64.pkg.tar.xz

 PKG_BINARY_AMD64 = releases/$(VERSION)/$(TOKEN_BINARY_AMD64)/$(FILE_BINARY_AMD64)
 PKG_BINARY_ARM64 = releases/$(VERSION)/$(TOKEN_BINARY_ARM64)/$(FILE_BINARY_ARM64)
+PKG_BINARY_RISCV64 = releases/$(VERSION)/$(TOKEN_BINARY_RISCV64)/$(FILE_BINARY_RISCV64)
 PKG_FEDORA-LATEST = releases/$(VERSION)/$(TOKEN_FEDORA-LATEST)/$(FILE_FEDORA-LATEST)
 PKG_FEDORA-OLDER = releases/$(VERSION)/$(TOKEN_FEDORA-OLDER)/$(FILE_FEDORA-OLDER)
 PKG_STREAM-LATEST = releases/$(VERSION)/$(TOKEN_STREAM-LATEST)/$(FILE_STREAM-LATEST)
@@ -110,6 +113,10 @@ DEP_BINARY_ARM64 =
 ifneq ($(TOKEN_BINARY_ARM64),)
        DEP_BINARY_ARM64 = $(PKG_BINARY_ARM64)
 endif
+DEP_BINARY_RISCV64 =
+ifneq ($(TOKEN_BINARY_RISCV64),)
+        DEP_BINARY_RISCV64 = $(PKG_BINARY_RISCV64)
+endif
 DEP_FEDORA-LATEST =
 ifneq ($(TOKEN_FEDORA-LATEST),)
        DEP_FEDORA-LATEST = $(PKG_FEDORA-LATEST)
@@ -497,6 +504,7 @@ release_test: $(DEP_BINARY_AMD64) $(DEP_BINARY_ARM64) $(DEP_FEDORA-LATEST) $(DEP

 release_binary_amd64: $(PKG_BINARY_AMD64)
 release_binary_arm64: $(PKG_BINARY_ARM64)
+release_binary_riscv64: $(PKG_BINARY_RISCV64)
 release_fedora-latest: $(PKG_FEDORA-LATEST)
 release_fedora-older: $(PKG_FEDORA-OLDER)
 release_stream-latest: $(PKG_STREAM-LATEST)
@@ -504,7 +512,7 @@ release_debian-stable: $(PKG_DEBIAN-STABLE)
 release_ubuntu-latest: $(PKG_UBUNTU-LATEST)
 release_archlinux: $(PKG_ARCHLINUX)

-releases/$(VERSION)/mgmt-release.url: $(DEP_BINARY_AMD64) $(DEP_BINARY_ARM64) $(DEP_FEDORA-LATEST) $(DEP_FEDORA-OLDER) $(DEP_STREAM-LATEST) $(DEP_DEBIAN-STABLE) $(DEP_UBUNTU-LATEST) $(DEP_ARCHLINUX) $(SHA256SUMS_ASC)
+releases/$(VERSION)/mgmt-release.url: $(DEP_BINARY_AMD64) $(DEP_BINARY_ARM64) $(DEP_BINARY_RISCV64) $(DEP_FEDORA-LATEST) $(DEP_FEDORA-OLDER) $(DEP_STREAM-LATEST) $(DEP_DEBIAN-STABLE) $(DEP_UBUNTU-LATEST) $(DEP_ARCHLINUX) $(SHA256SUMS_ASC)
        @echo "Pushing git tag $(VERSION) to origin..."
        git push origin $(VERSION)
        @echo "Creating github release..."
@@ -512,6 +520,7 @@ releases/$(VERSION)/mgmt-release.url: $(DEP_BINARY_AMD64) $(DEP_BINARY_ARM64) $(
                -F <( echo -e "$(VERSION)\n";echo "Verify the signatures of all packages before you use them. The signing key can be downloaded from https://purpleidea.com/contact/#pgp-key to verify the release." ) \
                ` [ -e $(PKG_BINARY_AMD64) ] && printf -- "-a $(PKG_BINARY_AMD64)" ` \
                ` [ -e $(PKG_BINARY_ARM64) ] && printf -- "-a $(PKG_BINARY_ARM64)" ` \
+               ` [ -e $(PKG_BINARY_RISCV64) ] && printf -- "-a $(PKG_BINARY_RISCV64)" ` \
                ` [ -e $(PKG_FEDORA-LATEST) ] && printf -- "-a $(PKG_FEDORA-LATEST)" ` \
                ` [ -e $(PKG_FEDORA-OLDER) ] && printf -- "-a $(PKG_FEDORA-OLDER)" ` \
                ` [ -e $(PKG_STREAM-LATEST) ] && printf -- "-a $(PKG_STREAM-LATEST)" ` \
@@ -528,6 +537,7 @@ releases/$(VERSION)/.mkdir:
        mkdir -p \
        ` [ "$(TOKEN_BINARY_AMD64)" != "" ] && printf -- "releases/$(VERSION)/$(TOKEN_BINARY_AMD64)/" ` \
        ` [ "$(TOKEN_BINARY_ARM64)" != "" ] && printf -- "releases/$(VERSION)/$(TOKEN_BINARY_ARM64)/" ` \
+       ` [ "$(TOKEN_BINARY_RISCV64)" != "" ] && printf -- "releases/$(VERSION)/$(TOKEN_BINARY_RISCV64)/" ` \
        ` [ "$(TOKEN_FEDORA-LATEST)" != "" ] && printf -- "releases/$(VERSION)/$(TOKEN_FEDORA-LATEST)/" ` \
        ` [ "$(TOKEN_FEDORA-OLDER)" != "" ] && printf -- "releases/$(VERSION)/$(TOKEN_FEDORA-OLDER)/" ` \
        ` [ "$(TOKEN_STREAM-LATEST)" != "" ] && printf -- "releases/$(VERSION)/$(TOKEN_STREAM-LATEST)/" ` \
@@ -547,6 +557,11 @@ $(PKG_BINARY_ARM64): build/mgmt-linux-arm64 releases/$(VERSION)/.mkdir
        @title='$(@D)' ; distro=$${title#'releases/$(VERSION)/'} ; echo "Building: $${distro} package..."
        @title='$(@D)' ; distro=$${title#'releases/$(VERSION)/'} ; cp -a build/mgmt-linux-arm64 $(PKG_BINARY_ARM64)
 endif
+ifneq ($(TOKEN_BINARY_RISCV64),)
+$(PKG_BINARY_RISCV64): build/mgmt-linux-riscv64 releases/$(VERSION)/.mkdir
+        @title='$(@D)' ; distro=$${title#'releases/$(VERSION)/'} ; echo "Building: $${distro} package..."
+        @title='$(@D)' ; distro=$${title#'releases/$(VERSION)/'} ; cp -a build/mgmt-linux-arm64 $(PKG_BINARY_RISCV64)
+endif
 ifneq ($(TOKEN_FEDORA-LATEST),)
 releases/$(VERSION)/$(TOKEN_FEDORA-LATEST)/changelog: $(PROGRAM) releases/$(VERSION)/.mkdir
        @title='$(@D)' ; distro=$${title#'releases/$(VERSION)/'} ; echo "Generating: $${distro} changelog..."
@@ -598,12 +613,13 @@ $(PKG_ARCHLINUX): $(PROGRAM) releases/$(VERSION)/.mkdir
        @title='$(@D)' ; distro=$${title#'releases/$(VERSION)/'} ; ./misc/fpm-pack.sh $${distro} $(VERSION) "$(FILE_ARCHLINUX)" libvirt augeas
 endif

-$(SHA256SUMS): $(DEP_BINARY_AMD64) $(DEP_BINARY_ARM64) $(DEP_FEDORA-LATEST) $(DEP_FEDORA-OLDER) $(DEP_STREAM-LATEST) $(DEP_DEBIAN-STABLE) $(DEP_UBUNTU-LATEST) $(DEP_ARCHLINUX)
+$(SHA256SUMS): $(DEP_BINARY_AMD64) $(DEP_BINARY_ARM64) $(DEP_BINARY_RISCV64) $(DEP_FEDORA-LATEST) $(DEP_FEDORA-OLDER) $(DEP_STREAM-LATEST) $(DEP_DEBIAN-STABLE) $(DEP_UBUNTU-LATEST) $(DEP_ARCHLINUX)
        @# remove the directory separator in the SHA256SUMS file
        @echo "Generating: sha256 sum..."
        sha256sum \
        ` [ -e $(PKG_BINARY_AMD64) ] && printf -- "$(PKG_BINARY_AMD64)" ` \
        ` [ -e $(PKG_BINARY_ARM64) ] && printf -- "$(PKG_BINARY_ARM64)" ` \
+       ` [ -e $(PKG_BINARY_RISCV64) ] && printf -- "$(PKG_BINARY_RISCV64)" ` \
        ` [ -e $(PKG_FEDORA-LATEST) ] && printf -- "$(PKG_FEDORA-LATEST)" ` \
        ` [ -e $(PKG_FEDORA-OLDER) ] && printf -- "$(PKG_FEDORA-OLDER)" ` \
        ` [ -e $(PKG_STREAM-LATEST) ] && printf -- "$(PKG_STREAM-LATEST)" ` \
```

I have no idea where to slot in `go mod tidy`, but considering that that is what it complained about, you might want to add it, somewhere. ^^

Kind regards,
Ingwie

**Comment by purpleidea** [comment]
> go mod tidy

Do you have the diff of what it recommended changing?

In any case, please feel free to send the above non go-mod changes as a pull request to review.
But there's at least one more area in the actual source code that needs patching too, so add that in. Grep around for aarch64 arm64 and so on, and you'll find it/them I'm sure.

> As for hardware... Well, actually, you can use QEMU

This is a fair point. I could experiment there, but I'm really interested in the whole bring up, from provisioning to hand-off, so I need some actual hardware. Here's an example of what I mean: https://purpleidea.com/blog/2024/03/27/a-new-provisioning-tool/

If you want to try that out for riscv, I'd love to hear about it.

**Comment by IngwiePhoenix** [comment]
> Do you have the diff of what it recommended changing?

```diff
diff --git a/go.mod b/go.mod
index 4410dd67..60864b13 100644
--- a/go.mod
+++ b/go.mod
@@ -1,6 +1,8 @@
 module github.com/purpleidea/mgmt

-go 1.20
+go 1.21
+
+toolchain go1.22.2

 require (
        github.com/alexflint/go-arg v1.4.3
@@ -13,6 +15,7 @@ require (
        github.com/docker/docker v25.0.4+incompatible
        github.com/docker/go-connections v0.5.0
        github.com/fsnotify/fsnotify v1.7.0
+       github.com/go-git/go-git/v5 v5.11.0
        github.com/godbus/dbus/v5 v5.1.0
        github.com/google/nftables v0.2.0
        github.com/google/uuid v1.6.0
@@ -37,6 +40,7 @@ require (
        go.etcd.io/etcd/client/pkg/v3 v3.5.12
        go.etcd.io/etcd/client/v3 v3.5.12
        go.etcd.io/etcd/server/v3 v3.5.12
+       go4.org/netipx v0.0.0-20231129151722-fdeea329fbba
        golang.org/x/crypto v0.21.0
        golang.org/x/sys v0.18.0
        golang.org/x/time v0.5.0
@@ -68,7 +72,6 @@ require (
        github.com/felixge/httpsnoop v1.0.4 // indirect
        github.com/go-git/gcfg v1.5.1-0.20230307220236-3a3c6141e376 // indirect
        github.com/go-git/go-billy/v5 v5.5.0 // indirect
-       github.com/go-git/go-git/v5 v5.11.0 // indirect
        github.com/go-logr/logr v1.4.1 // indirect
        github.com/go-logr/stdr v1.2.2 // indirect
        github.com/gogo/protobuf v1.3.2 // indirect
@@ -111,6 +114,7 @@ require (
        github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd // indirect
        github.com/modern-go/reflect2 v1.0.2 // indirect
        github.com/morikuni/aec v1.0.0 // indirect
+       github.com/nxadm/tail v1.4.11 // indirect
        github.com/opencontainers/go-digest v1.0.0 // indirect
        github.com/opencontainers/image-spec v1.1.0-rc2 // indirect
        github.com/pierrec/lz4/v4 v4.1.21 // indirect
@@ -147,7 +151,6 @@ require (
        go.uber.org/atomic v1.11.0 // indirect
        go.uber.org/multierr v1.11.0 // indirect
        go.uber.org/zap v1.23.0 // indirect
-       go4.org/netipx v0.0.0-20231129151722-fdeea329fbba // indirect
        golang.org/x/exp v0.0.0-20240112132812-db7319d0e0e3 // indirect
        golang.org/x/mod v0.16.0 // indirect
        golang.org/x/net v0.22.0 // indirect
```
You mean this?

> I'm really interested in the whole bring up, from provisioning to hand-off
Most of that happens via u-boot! I actually spent a significant amount of time with this topic too - but more in terms of getting a more upstream kernel working (which is what I did and am currently booted into on that box, and which has been very stable). Next step is to get some GPU drivers in, but the GPU in the VisionFive2 is really more for show than anything; not exactly the most powerful iGPU out there :) Still, it exists.

I have yet to read the whole blog post (I am visually impaired, reading long blurbs of text takes me quite a while) but u-boot supports tftp booting. So technically, if you were to provision a microSD with a super simplistic u-boot script that just boots into a network boot, you could provision the entire system from there. Do be aware of DTBs though!

Will give the blog post a read in a bit and see if there is anything more I can tell you about this. :)

**Comment by purpleidea** [comment]
> +go 1.21

We won't be moving the golang version forward until about a week or two. So no need to include anything related to go.mod in the patch.

> +toolchain go1.22.2

I actually have no idea what this line even does! (go.mod and I are not friends)

> You mean this?

Yes thanks!

> I am visually impaired, reading long blurbs of text takes me quite a while

While I was I could have made the blog post shorter, is there any simple advice you'd have for structuring it better?

Thanks for the comments. I will close this issue now, but please open a PR about riscv if you'd like. We also have a matrix channel which is more appropriate for discussion/hacking etc.

Cheers!

**Comment by IngwiePhoenix** [comment]
> (go.mod and I are not friends)

I relate to that. A lot. xD

> While I was I could have made the blog post shorter, is there any simple advice you'd have for structuring it better?

None I could think of. Just finished reading it in fact. Good paragraphing and contextual separation helps a lot when people like me take a short break. Helps to pick up where we left off. Kind of like state management... Jokes aside, I have nothing to improve here. However, formating wise, please do make the sub-headings a little bigger. Whilst I already do use a screen magnifier - Windows has one built in, MacOS does too; Linux' is "present" at best... - it helps to pick up the start and end of a paragraph better. But that's really the only thing I could think of.

> We also have a matrix channel(...)

My Dendrite is on strike since the last update. Once I have that fixed, I will come say hi. ^^

**Comment by purpleidea** [comment]
FYI: I actually hit what might be a similar issue to your aforementioned build issue on aarch64, and I added a small improvement in the error message: 6b12632bf076a672dde304d4c17edbf75e653244
