### ISSUE TITLE
add lxc support to virt resource

### ISSUE THREAD

**Issue by joejulian** [purpleidea/mgmt#84]
libvirt can manage lxc containers with the url lxc:/// which does not work with the virt resource.

**Comment by purpleidea** [comment]
Indeed this was not tested, but there is a URI variable https://godoc.org/github.com/purpleidea/mgmt/resources#VirtRes which is meant to be used to support things like this.

What is the error you're getting to indicate that it doesn't work?

**Comment by joejulian** [comment]
```
11:32:06 virt.go:346: Virt[mgmt1]: CheckApply(true)
11:32:06 pgraph.go:738: Virt[mgmt1]: CheckApply errored: LookupDomainByName failed: [Code-42] [Domain-17] Domain not found: No domain with matching name 'mgmt1'
11:32:06 pgraph.go:881: Virt[mgmt1]: Exited with failure: LookupDomainByName failed: [Code-42] [Domain-17] Domain not found: No domain with matching name 'mgmt1'
11:32:06 virt.go:137: EventRunDefaultImpl exited!
```

**Comment by purpleidea** [comment]
This looks implemented now, closing.
