### ISSUE TITLE
System package dependencies in installation documentation

### ISSUE THREAD

**Issue by LrsK** [purpleidea/mgmt#98]
I tried installing mgmt by following the quickstart guide on an Ubuntu 16.04 LTS machine.  I get the following error:

```
➜  ~ go get -u github.com/purpleidea/mgmt
# github.com/rgbkrk/libvirt-go
dev/go/src/github.com/rgbkrk/libvirt-go/cfuncs.go:6:29: fatal error: libvirt/libvirt.h: No such file or directory
compilation terminated.
```

After running ``` sudo apt-get install libvirt-dev ``` this message disappears, but when attempting ``` go get ./... ``` I get arrors about pcap.h and systemd/sd-journal.h. After ``` sudo apt-get install libpcap-dev libsystemd-dev ``` these errors went away. 

Should these dependencies be listed in the docs, or are they so system dependent that the user will have to figure this out for their system?

**Comment by purpleidea** [comment]
Technically these deps are listed in the deps script.

https://github.com/purpleidea/mgmt/blob/master/misc/make-deps.sh#L21

You're right that this could be clearer. Any recommendations? (Maybe a patch?)
